### ISSUE TITLE
Cannot import project

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [BigBadaboom/androidsvg#104]
Got this error:

Error:Unable to find method 'org.gradle.api.internal.project.ProjectInternal.getPluginManager()Lorg/gradle/api/internal/plugins/PluginManagerInternal;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by BigBadaboom** [comment]
This should be fixed.  I have updated all the build tools versions and updated build configs etc.  Compiles for me now.

**Comment by AndroidDeveloperLB** [comment]
Hmmm... for some reason I don't see anything launchable:

![image](https://cloud.githubusercontent.com/assets/5357526/26404389/666668ca-409a-11e7-980b-c12fdf5d96d4.png)

**Comment by BigBadaboom** [comment]
@AndroidDeveloperLB This is a library project. There is nothing to run here.  It will need to be imported into your app, and accessed via the API.  Or wait till I release v1.2.3 as an AAR.

**Comment by AndroidDeveloperLB** [comment]
Is there an easy way to test it then?
It's a very common thing for libraries here on Github to have a sample...

**Comment by BigBadaboom** [comment]
Are you wanting to test this particular version, or just this library in general?  I assume the latter if you don't already have a project you can import it to.

I will consider adding a sample project to the repo. In the meantime, you could perhaps try the sample project that comes with the Glide library. It uses this library to handle SVG images.

https://github.com/bumptech/glide/tree/master/samples/svg

**Comment by AndroidDeveloperLB** [comment]
Thanks. Please do consider adding a sample, showing the cool things this library can do.
About the link, please consider adding it to main page of the repo, for now.
