### ISSUE TITLE
Wrong parsing font-family at style

### ISSUE THREAD

**Issue by KirillMakarov** [BigBadaboom/androidsvg#105]
For example, 
svg is:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 150 150">
	<text text-anchor="middle" fill="white" x="75.0" y="93.0" style="font-family: Roboto, sans-serif; font-size: 50.0px; letter-spacing:0.05em">Something</text></svg>`

style will be wrong parsed, because of whitespace is delimiter symbol [here](https://github.com/BigBadaboom/androidsvg/blob/master/androidsvg/src/main/java/com/caverock/androidsvg/SVGParser.java#L2599). Instead of "font-family: Roboto, sans-serif" will be parsed "font-family: Roboto,". At the next iteration "sans-serif" will break the cycle, and **all** attrs of style won't be parsed.

For parsing the "style" another nextToken should be used, where whitespace is not delimiter (the name of font can be 'Times New Roman'). style tag specifiacation is [here](http://www.allsyllabus.com/aj/note/Computer_Science/Programming%20the%20Web/Unit3-SY/Style%20Specification%20Formats.php#.WL6PdxLyjRZ)

**Comment by BigBadaboom** [comment]
Fixed handling of CSS properties with spaces in values.
