### ISSUE TITLE
svg font_family are not included in android

### ISSUE THREAD

**Issue by JeckChou** [BigBadaboom/androidsvg#109]
my svg file have some text with font_family, and they are not included in android . how to import ttf font file into svg with this lib? 

```
<text id="text-3" font-family="Roboto-Black, Roboto" font-size="38" font-weight="700" fill="#FFFFFF">
            <tspan x="145" y="699">text</tspan>
 </text>

```
thanks.

**Comment by BigBadaboom** [comment]
Please see the secion of the documentation on resolving external references.

http://bigbadaboom.github.io/androidsvg/api_summary.html

Questions about AndroidSVG should be sent to the feedback address androidsvgfeedback@gmail.com. Please only create an issue if you find a bug or have a feature request.
