### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by mstevens83** [BigBadaboom/androidsvg#110]
I was just wondering if there are plans for a new (stable) release in the near future or whether this project is unlikely to progress anymore. And in the latter case, is anyone aware of an actively developed fork or alternative?

**Comment by BigBadaboom** [comment]
Yes. I have recently started fixing bugs and implementing feature requests again. There will be a new release in the not-too-distant future.

**Comment by mstevens83** [comment]
That's great news! Thanks for your efforts!

Op 28 jun. 2017 1:32 p.m. schreef "Paul LeBeau" <notifications@github.com>:
