### ISSUE TITLE
show black background and corrupted

### ISSUE THREAD

**Issue by HaDiSs277** [BigBadaboom/androidsvg#111]
Hi, Thank you for your great library.
I am using your library for viewing svg files by using SVGImageView. i dont render them by myself.
Every thing was great until i tested the app on Android Ice_cream and jelly beans...
In both of them some of svg file not render and some has black background and some of them are corrupted..
What's wrong?
Can you help me please? i need your help.
I attached some screen shots of issue and those svg files.
It happen on Galaxy Duos and Huawei Y 300.
Thanks for response.
![photo_2017-07-01_15-33-03](https://user-images.githubusercontent.com/18545439/27767393-f15a89ae-5f0b-11e7-882c-7a5817bdc509.jpg)
![photo_2017-07-01_15-33-08](https://user-images.githubusercontent.com/18545439/27767394-f181ef12-5f0b-11e7-8ab5-ac7292b71dc8.jpg)
![photo_2017-07-01_15-34-44](https://user-images.githubusercontent.com/18545439/27767395-f18417ec-5f0b-11e7-8070-7145685908cd.jpg)
[svg_files.zip](https://github.com/BigBadaboom/androidsvg/files/1117630/svg_files.zip)

**Comment by HaDiSs277** [comment]
i use them inside custom RadioGroup. 
This is my Xml:
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:SetOnCheckedChangeListener="http://schemas.android.com/apk/res-auto"
    tools:context="fragment.practices.PracticeType1_Fragment"
    android:orientation="vertical">

    

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="New Radio"
        android:id="@+id/txtQuestion"
        android:gravity="center_vertical|right"
        android:textColor="@color/black"
        android:textStyle="bold"
        android:layout_marginBottom="@dimen/type1_padding"
        android:textSize="@dimen/large_font_size"
        android:paddingRight="6dp" />

    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:layout_marginBottom="@dimen/type1_padding">

        <helper.MyRadioGroup
            android:layout_width="match_parent"
            android:layout_height="match_parent"

            android:id="@+id/rgp">
            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical"
                >
                <LinearLayout
                    android:orientation="horizontal"
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    android:layout_weight="0.5"
                    android:gravity="center">

                    <RelativeLayout
                        android:layout_width="0dp"
                        android:layout_height="match_parent"
                        android:layout_weight="0.5"
                        android:id="@+id/rtl2"
                        android:paddingRight="@dimen/padding_vertical"
                        android:paddingBottom="@dimen/padding_vertical">

                        <FrameLayout
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:id="@+id/frm2"
                            android:background="@drawable/rect_gray_stoke"></FrameLayout>

                        <RadioButton
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:text="Radio button"
                            android:id="@+id/rbtn2"
                            android:layout_alignParentBottom="true"
                            android:layout_alignParentRight="false"
                            android:drawableLeft="@drawable/selector_radio_button"
                            android:button="@null"
                            android:drawablePadding="10dp"
                            android:gravity="center_vertical|left"
                            android:textSize="@dimen/normal_font_size"
                            android:textColor="@color/black"
                            android:layout_alignParentLeft="true"
                            android:paddingLeft="@dimen/padding_vertical_big"
                            android:paddingBottom="@dimen/padding_vertical" />

                        <com.caverock.androidsvg.SVGImageView
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:id="@+id/img2"
                            android:layout_above="@+id/rbtn2"
                            android:adjustViewBounds="true"
                            android:clickable="false"
                            android:padding="@dimen/padding_vertical" />
                    </RelativeLayout>

                    <RelativeLayout
                        android:layout_width="0dp"
                        android:layout_height="match_parent"
                        android:layout_weight="0.5"
                        android:id="@+id/rtl1"
                        android:paddingLeft="@dimen/padding_vertical"
                        android:paddingBottom="@dimen/padding_vertical">

                        <FrameLayout
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:id="@+id/frm1"
                            android:background="@drawable/rect_gray_stoke"></FrameLayout>

                        <RadioButton
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:text="Radio button"
                            android:id="@+id/rbtn1"
                            android:layout_alignParentBottom="true"
                            android:layout_alignParentRight="false"
                            android:drawableLeft="@drawable/selector_radio_button"
                            android:button="@null"
                            android:drawablePadding="10dp"
                            android:gravity="left|center_vertical"
                            android:textSize="@dimen/normal_font_size"
                            android:textColor="@color/black"
                            android:layout_alignParentLeft="true"
                            android:paddingLeft="@dimen/padding_vertical_big"
                            android:paddingBottom="@dimen/padding_vertical" />

                        <com.caverock.androidsvg.SVGImageView
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:id="@+id/img1"
                            android:layout_above="@+id/rbtn1"
                            android:adjustViewBounds="true"
                            android:clickable="false"
                            android:padding="@dimen/padding_vertical" />
                    </RelativeLayout>

                </LinearLayout>

                <LinearLayout
                    android:orientation="horizontal"
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    android:layout_weight="0.5"
                    android:gravity="center">

                    <RelativeLayout
                        android:layout_width="0dp"
                        android:layout_height="match_parent"
                        android:layout_weight="0.5"
                        android:id="@+id/rtl4"
                        android:paddingTop="@dimen/padding_vertical"
                        android:paddingRight="@dimen/padding_vertical">

                        <FrameLayout
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:id="@+id/frm4"
                            android:background="@drawable/rect_gray_stoke"></FrameLayout>

                        <RadioButton
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:text="Radio button"
                            android:id="@+id/rbtn4"
                            android:layout_alignParentBottom="true"
                            android:layout_alignParentRight="false"
                            android:drawableLeft="@drawable/selector_radio_button"
                            android:button="@null"
                            android:drawablePadding="10dp"
                            android:gravity="left|center_vertical"
                            android:textSize="@dimen/normal_font_size"
                            android:textColor="@color/black"
                            android:layout_alignParentLeft="true"
                            android:paddingLeft="@dimen/padding_vertical_big"
                            android:paddingBottom="@dimen/padding_vertical" />

                        <com.caverock.androidsvg.SVGImageView
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:id="@+id/img4"
                            android:layout_above="@+id/rbtn4"
                            android:adjustViewBounds="true"
                            android:clickable="false"
                            android:padding="@dimen/padding_vertical" />
                    </RelativeLayout>

                    <RelativeLayout
                        android:layout_width="0dp"
                        android:layout_height="match_parent"
                        android:layout_weight="0.5"
                        android:id="@+id/rtl3"
                        android:paddingTop="@dimen/padding_vertical"
                        android:paddingLeft="@dimen/padding_vertical">

                        <FrameLayout
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:id="@+id/frm3"
                            android:background="@drawable/rect_gray_stoke"></FrameLayout>

                        <RadioButton
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:text="Radio button"
                            android:id="@+id/rbtn3"
                            android:layout_alignParentBottom="true"
                            android:layout_alignParentRight="false"
                            android:drawableLeft="@drawable/selector_radio_button"
                            android:button="@null"
                            android:drawablePadding="10dp"
                            android:gravity="left|center_vertical"
                            android:textSize="@dimen/normal_font_size"
                            android:textColor="@color/black"
                            android:layout_alignParentLeft="true"
                            android:paddingLeft="@dimen/padding_vertical_big"
                            android:paddingBottom="@dimen/padding_vertical" />

                        <com.caverock.androidsvg.SVGImageView
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:id="@+id/img3"
                            android:layout_above="@+id/rbtn3"
                            android:adjustViewBounds="true"
                            android:clickable="false"
                            android:padding="@dimen/padding_vertical" />
                    </RelativeLayout>
                </LinearLayout>
            </LinearLayout>



        </helper.MyRadioGroup>



    </LinearLayout>

<include layout="@layout/buttons_check"/>

</LinearLayout>
`
 And in fragment i did it:
`img1.setImageAsset("svg/practice/"+practice.practiceData.options.get(0).toLowerCase()+".svg");
        img2.setImageAsset("svg/practice/"+practice.practiceData.options.get(1).toLowerCase()+".svg");
        img3.setImageAsset("svg/practice/"+practice.practiceData.options.get(2).toLowerCase()+".svg");
        img4.setImageAsset("svg/practice/"+practice.practiceData.options.get(3).toLowerCase()+".svg");`

its ok on android +5. but in 4.2 and 4.0 in my devices not worked correctly.
Do you have any solution for these android version?

**Comment by BigBadaboom** [comment]
I notice that the two country SVGs are actually just a single PNG image element.   If it always works fine in 5, but fails in 4.0 and 4.2, then that would suggest that it is a PNG parsing problem in those versions of Android.  You could perhaps solve that particular problem by converting those files to proper vector SVG files.  However I will experiment and see if I can reproduce the problem.

Which version of AndroidSVG are you using?

**Comment by BigBadaboom** [comment]
Also, in email you said:
> Some times these are correct and some times they have black background and some times not show any thing.

Can you tell me anything about the times that these errors happen? Is there any common factors that might give a hint as to the cause?

**Comment by HaDiSs277** [comment]
Hi, Thanks for response.
I downloaded your library completely 2 or 3 month ago.
I tried to convert PNGs file of countries to SVG by online tools.
Now they are correct in in Huawei Y330 and Rayan phone , i mean they are not corrupted again.
But until in Galaxy win Duos all of my SVGs file has black background. they are not transparent.

**Comment by BigBadaboom** [comment]
I have been able to reproduce the corrupted image problem with a test program.  I will investigate why it is happening.

I have not been able to reproduce the black background problem though.  Can you perhaps experiment and see if you can work out what causes it?  For example, try systematically removing widgets and attributes from the RelativeLayout for one of your cells.

**Comment by HaDiSs277** [comment]
Yes of course.
I will do it, and send it's feed back.

**Comment by HaDiSs277** [comment]
Hi,
I experimented the SVGImageView by various ways, finally i find the problem.
I had a FrameLayout in a  RelativeLayout in my XML that SVGImageView was above of all views, my FrameLayout had a background just with stroke, like this:
`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle" >
     <stroke android:width="2dp" android:color="@color/gray_chk"/>
    <corners android:radius="2dp"/>
</shape>`
and finally when i add this line to drawable:
`  <solid android:color="@android:color/transparent" />`
The SVGImageView became transparent!!!
It was really ridiculous!

**Comment by BigBadaboom** [comment]
Great! That's one problem solved. I will be working on fixing the other problem this weekend.

**Comment by BigBadaboom** [comment]
I have been investigating the corruption issue.  I am now satisfied that it is not a bug in AndroidSVG.

The bug only seems to manifest when you use `renderToPicture()` and then try to draw that `Picture` later.  Unfortunately, that's what SVGImageView does - it creates a `PictureDrawable` and assigns that to the `ImageView` that it inherits from.

The good news is that there is a workaround.  It doesn't seem to happen if you use `renderToCanvas()`.  However that means that you'll either need to do the rendering yourself, or modify `SVGImageView` so that it uses `renderToCnvas()` instead.

For example, if you copy `SVGImageView` into your own code and modify the following inner class, it should fix your problem.  **However please note this is a hacky fix that creates a backing `Bitmap` that is the size of the SVG `width` and `height`.  You'll probably want to improve this code so that it uses a Bitmap the size of the View.**

```
   private class LoadAssetTask extends AsyncTask<String, Integer, Bitmap>
   {
      private Context  context;
      private String   filename;

      LoadAssetTask(Context context, String filename)
      {
         this.context = context;
         this.filename = filename;
      }

      protected Bitmap  doInBackground(String... params)
      {
         try
         {
            SVG  svg = SVG.getFromAsset(context.getAssets(), filename);
            Bitmap  newBM = Bitmap.createBitmap(Math.round(svg.getDocumentWidth()), Math.round(svg.getDocumentHeight()), Bitmap.Config.ARGB_8888);
            Canvas bmcanvas = new Canvas(newBM);
            svg.renderToCanvas(bmcanvas);
            return newBM;
         }
         catch (SVGParseException e)
         {
            Log.e("SVGImageView", "Error loading file " + filename + ": " + e.getMessage());
         }
         catch (FileNotFoundException e)
         {
            Log.e("SVGImageView", "File not found: " + filename);
         }
         catch (IOException e)
         {
            Log.e("SVGImageView", "Unable to load asset file: " + filename, e);
         }
         return null;
      }

      protected void  onPostExecute(Bitmap picture)
      {
         if (picture != null) {
            setSoftwareLayerType();
            setImageBitmap(picture);
         }
      }
   }
```

I have plans to rework SVGImageView to fix other problems with the current version. When I do, it will likely use a `Bitmap` instead of a `Picture`. However I am not sure when I will get to that.

Anyway, I hope this is of some help...  good luck with your project.
