### ISSUE TITLE
Render svg bug

### ISSUE THREAD

**Issue by MaksTuev** [BigBadaboom/androidsvg#116]
This resource draw as black rectangle https://drive.google.com/open?id=0B9HiaK6QQBxKeFZEaFdDSy1qSGc

**Comment by BigBadaboom** [comment]
@MaksTuev That file is not publically accessible. Please add it as an attachment it to this bug.

**Comment by BigBadaboom** [comment]
Closing due to lack of response.  I will be happy to reopen if you make the file available.
