### ISSUE TITLE
text-anchor attribute does not behave according to specification

### ISSUE THREAD

**Issue by SimulPiscator** [BigBadaboom/androidsvg#118]
### SVG Specification:
> The text-anchor attribute is applied to each individual text chunk within a given `<text>` element. Each text chunk has an initial current text position, which represents the point in the user coordinate system resulting from (depending on context) application of the x and y attributes on the `<text>` element, any x or y attribute values on a `<tspan>`, `<tref>` or `<altGlyph>` element assigned explicitly to the first rendered character in a text chunk, or determination of the initial current text position for a `<textPath>` element.

### Example:
```
<text style='text-anchor: end'>
  <tspan x='346' y='22'>example</tspan>
</text>
```

### Expected outcome:
Text "example" should end at x position 346.

### Actual outcome:
Text "example" begins at x position 346.

**Comment by BigBadaboom** [comment]
Thanks for the report!  I will take a look at this bug.

**Comment by BigBadaboom** [comment]
Fixed bug with text-anchor alignment wasn't being recalculated if x was specified on a child tspan.
