### ISSUE TITLE
Feature request: Add custom layouts with SVG background

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#12]
```
Will be very usefull to add SVGLinearLayout, SVGRelativeLayout etc. with 
opportunity to set background as svg file according to SVGImageView.


```

Original issue reported on code.google.com by `step.8...@gmail.com` on 14 Aug 2013 at 9:47

**Comment by BigBadaboom** [comment]
Marking Won't Fix. There are easy ways to achieve this (such as putting an SVGImageView behind the LinearLayout.  I don't think many people would use this.
