### ISSUE TITLE
Embedded base64 PNGs not rendered correctly

### ISSUE THREAD

**Issue by spurgeon** [BigBadaboom/androidsvg#121]
The embedded base64 PNGs (with masks) are not rendered correctly for this SVG file: [Brauen_einfach.svg](https://minecraft-de.gamepedia.com/Datei:Brauen_einfach.svg)

Is there a solution for this?  Perhaps it's caused by some of the logic in SVGAndroidRenderer.render(SVG.Image obj)?

`SVG svg = SVG.getFromInputStream(new FileInputStream(path));`
`Bitmap newBM = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);`
`Canvas canvas = new Canvas(newBM);`
`canvas.drawRGB(255, 255, 255);`
`svg.renderToCanvas(canvas);`
`return newBM;`

Here's what I'm seeing: 
![screen shot 2017-12-04 at 12 11 31 pm](https://user-images.githubusercontent.com/6686414/33569114-41bcddaa-d8ee-11e7-860c-dc3731112ef6.jpg)

Here's what I expect: 
![screen shot 2017-12-04 at 12 17 26 pm](https://user-images.githubusercontent.com/6686414/33569122-4ae5a402-d8ee-11e7-8784-b4de7b1b3be4.jpg)

**Comment by BigBadaboom** [comment]
Attached sample file for future reference.:
[Brauen_einfach.zip](https://github.com/BigBadaboom/androidsvg/files/1529308/Brauen_einfach.zip)

**Comment by BigBadaboom** [comment]
Hi. Which version of the library are you using?

When I test with the latest (unreleased) build, the images are showing okay, they just aren't masked properly.  So most of them have a dark background.  I am looking into why that is.,

**Comment by spurgeon** [comment]
I'm using the latest source, actually, but I also observed the behavior with 1.2.1.  I noticed a slightly different image than the one I posted previously when run on a real device versus an emulator.  As a guess, perhaps the issue is related to device DPI?  Here's what I see on LG Nexus 5X (notice the black "dots" are different than the one I sent previously on an emulator):

![screen shot 2017-12-08 at 3 32 22 pm](https://user-images.githubusercontent.com/6686414/33786184-b335f952-dc2d-11e7-8f3f-06222768ccca.png)

**Comment by BigBadaboom** [comment]
Fixed.

Note that rendering your original image takes a long time. That's because the code that processes masks is very slow.  That's on the list of things to fix (see issue #45).

If you want it to go faster, fix the SVG so that it uses transparent PNGs rather than masked images.

**Comment by spurgeon** [comment]
Thanks, confirmed the fix from my end.  I am using the library to view existing SVGs that users have, so I can't "fix" the SVG so that it renders faster.

**Comment by BigBadaboom** [comment]
You might want to pull the latest version of the library.  I've just pushed a patch that implements masks a much better way.  The SVG above now renders around 20x faster.

**Comment by spurgeon** [comment]
Thank you!  It's much faster like you said.
