### ISSUE TITLE
Is there a way of changing fill color?

### ISSUE THREAD

**Issue by siralam** [BigBadaboom/androidsvg#124]
Assume that I cannot change the source of the SVG file (well, I can hard-code to replace strings of the svg, but not really prefered),

Can I change the color of the image rendered?

Below is the major part of the code for me to generate the `PictureDrawable`:
```java
            SVG svg = SVG.getFromString(html);
            svg.setDocumentHeight(String.valueOf(height));
            svg.setDocumentWidth(String.valueOf(width));
            Drawable drawable = new PictureDrawable(svg.renderToPicture());
            return drawable;
```

The above code produces a black image.

The first thing (of course) I come up with is to try to set a ColorFilter to the PictureDrawable. But that does not work.

I have tried:
```java
drawable.setColorFilter(getResources().getColor(android.R.color.white), PorterDuff.Mode.SRC_ATOP);
```

Or 

```java
drawable.mutate().setColorFilter(getResources().getColor(android.R.color.white), PorterDuff.Mode.SRC_ATOP);
```

As for different `PorterDuff.Mode`, I have tried `SRC_ATOP`, `SRC_IN`, `MULTIPLY`, `OVERLAY`, all simply produces completely black image.

**Comment by BigBadaboom** [comment]
The issue tracker is intended more for bug reports and feature requests than questions.  Can you resend this in an email to androidsvgfeedback@gmail.com please. Or better still, post it as a question to stackoverflow.com so answers can help other people.

**Comment by BigBadaboom** [comment]
Currently AndroidSVG is a viewer only. There are no methods for modifying the content of the SVG other than the `setDocumentXX()` methods.
