### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by williamsjj** [BigBadaboom/androidsvg#126]
We're currently using the 1.2.1 release that's marked from 2014. Will there be a new release at some point or is everyone just using Master?

**Comment by BigBadaboom** [comment]
There's a 1.2.2-beta that is fine to use. (I never ended unded up creating the final 1.2.2 relase. :-/

I'm in the middle of a bug fixing spree right now.  I will be releasing a 1.3 as soon as  I am done.

**Comment by williamsjj** [comment]
Awesome. I'll keep an eye out.
