### ISSUE TITLE
SVG renders blank on Android < 7.0

### ISSUE THREAD

**Issue by williamsjj** [BigBadaboom/androidsvg#127]
I've been having a weird issue I'm not sure how to debug. The following code works fine on Android 7.0+, but results in a blank space of the correct size on Android 5.0 and 6.0:

```
logo = new ImageView(this.getActivity());
try {
    logo.setImageDrawable(
            new PictureDrawable(
                    SVG.getFromResource(this.getActivity(), R.drawable.logo)
                    .renderToPicture(
                            kLOGO_WIDTH_DP,
                            kLOGO_HEIGHT_DP)));
} catch (Exception e) {
    throw new AssertionError("Can't load logo. Shouldn't be here.");
}
```

Any pointers are greatly appreciated.

**Comment by BigBadaboom** [comment]
Stupid first question: are you doing the `addView()` call to add it to the layout?

Does it work with other SVGs?  Are you getting any errors in the LogCat?

**Comment by williamsjj** [comment]
Yeah, I just left that part out...goes below the above:

```
RelativeLayout.LayoutParams logo_layout_params =
                new RelativeLayout.LayoutParams(kLOGO_WIDTH_DP, kLOGO_HEIGHT_DP);
logo_layout_params.setMargins(30, 0, 30, 0);
logo_layout_params.addRule(RelativeLayout.CENTER_HORIZONTAL, RelativeLayout.TRUE);
logo_layout_params.addRule(RelativeLayout.ALIGN_PARENT_TOP, RelativeLayout.TRUE);
wpmLogo.setLayoutParams(logo_layout_params);
wrapper.addView(wpmLogo);
```

Works great if the OS is Android 7+. I have two SVG resources in the view, both show up on Android 7+, neither appear on 5.0 or 6.0.

**Comment by BigBadaboom** [comment]
Interesting... Are you setting a scaleType, or using the default value?  "center" and "fitXY" don't work with PictureDrawables.
Also try the 1,2,2 beta and see if that makes a difference (it is safe to use in prod).

**Comment by williamsjj** [comment]
I'm not setting a scaleType. The 1.2.2 beta that's under releases/tagged out from 2014 or pull master?

**Comment by BigBadaboom** [comment]
There's a 1.2.2 in the Maven Central repo: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.caverock%22

Or you could try building from master. It has a number of fixes and improvements.

**Comment by williamsjj** [comment]
Setting `logo.setLayerType(View.LAYER_TYPE_SOFTWARE, null)` fixes it.

**Comment by BigBadaboom** [comment]
Ah. Yes. Forgot to ask that. It should have been my first question... :/  Good luck with your project.

**Comment by williamsjj** [comment]
Thank you! Very much appreciate your help. Thank you for maintining a great library.
