### ISSUE TITLE
Text is not aligned

### ISSUE THREAD

**Issue by filipedelimabrito** [BigBadaboom/androidsvg#129]
I have a SVG file with a `rect` and `text` element. The `text` should be aligned in the center of the `rect`. 

The SVG file is as follow:

```
<svg xmlns="http://www.w3.org/2000/svg">
   <rect width="100%" height="100%" rx="6" ry="6" fill="#607D1B" />
   <text x="45%" y="60%" fill="#ffffff" font-family="Helvetica, Arial, Lucida Grande, sans-serif" font-size="50">F</text>
</svg>

```

On the browser, the SVG file is displayed as expected (you can simple change the extension file from .svg to .html to confirm it), looking like this:

![screen shot 2018-02-01 at 7 51 44 am](https://user-images.githubusercontent.com/11776825/35674911-f64278d4-0724-11e8-91ea-37d469f2f4e0.png)

But when using `androidsvg` library I get this weird result:

![photo_2018-02-01_07-59-42](https://user-images.githubusercontent.com/11776825/35675217-051e1678-0726-11e8-81c1-2103ab8be980.jpg)

Note: I'm using the latest changes made in this library by adding this project as a module in my application, because the [last release](http://bigbadaboom.github.io/androidsvg/download.html) available in the Maven Central Repository was 4 years ago :scream:

**Comment by BigBadaboom** [comment]
Hi Filipe. Thanks for the bug report.

AndroidSVGs rendering could be valid.  The SVG doesn't have a `width` or `height`, so how it renders will depend solely on how big you are drawing the SVG.

In the case of the browser, it is likely defaulting to the standard 300x150 size that the HTML uses for dimensions that are indeterminate.

That won't be the case for your app.  What size are you using?  Are you drawing it yourself into a view? Or are you using an SVGImageView or ImageView?

From your android screenshot, it looks like the size is 80x80.  If we specify that size in a browser, we get the same result:

https://jsfiddle.net/b46kk2v5/1/

**Comment by filipedelimabrito** [comment]
Hi @BigBadaboom. Thanks for your response. 

I'm using androidsvg library with Fresco library. As you can see [here](https://github.com/RocketChat/Rocket.Chat.Android/blob/cf8c65135b399f3ab9ea299106ae349c3d0109de/app/src/main/res/layout/avatar.xml#L9) the width and height of the image are defined in `40dp` and `40dp`, respectively.
 
The size of the image is drawn correctly, but the problem comes when showing the text inside it.

As pointed by you the SVG file doesn't have the width and height elements and after adding it I finally get the desired result in the Android application. 

Additional note: from the [jsfiddle link](https://jsfiddle.net/b46kk2v5/1/) above (really thanks for providing it - helped me a lot) if, for instance, we change the text from "F" to "W", we can see that the position of the text changes. So In order to make the text centralised (working fine for any alphabetical letter) I had to add others elements, as seen here: https://jsfiddle.net/filipedelimabrito/54gy635j/


It is nice to see this library [in use](https://github.com/facebook/fresco/blob/559082930126c05988f46de8f27fccad0dd88568/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat/svg/SvgDecoderExample.java#L17) with Fresco and it would be really nice to see the updates made to this library available in the Maven Central Repository ❤️ 

Thank you!

**Comment by BigBadaboom** [comment]
Instead of specifying a particular `width` and `height`, another, possibly better, option would be to specify a `viewBox` instead. That way the SVG should look correct no matter what size you make it.

https://jsfiddle.net/b46kk2v5/2/

> it would be really nice to see the updates made to this library available in the Maven Central Repository

A new version will be released soon.  As soon as I am finished with my current bug fixing spree. :)

**Comment by filipedelimabrito** [comment]
Really appreciate your efforts and your advice. Let me know if you have a personal or project account (pay pal, whatever) to support you - a coffee or a drink would fit well.

Thank you!

**Comment by BigBadaboom** [comment]
Thank you for the offer. but no donation is necessary.

Is it okay to tweet or otherwise publicise that AndroidSVG is used in RocketChat?
