### ISSUE TITLE
usage with PhotoView

### ISSUE THREAD

**Issue by fyn-dev** [BigBadaboom/androidsvg#131]
It could be nice if this library could more extendable and have option to use with libraries like [PhotoView](https://github.com/chrisbanes/PhotoView). For now when I use  PictureDrawable as drawable and pass to  PhotoView with close zoom it not give good quality. But if I use drawable from svg as native android vector asset it zoom with PhotoView library without any issues.

Can you provide some kind of toDrwable function which create drawable object which we can zoom without any issue with loosing quality (same what we have in Vector Asset as drwable of Android Studio)?
 
Or how to make fast zoom render and scroll with your library? My code:

```
val svg = SVG.getFromAsset(this.applicationContext.assets, "some_graphic.svg")
val drawable = PictureDrawable(svg.renderToPicture())
photoView.setImageDrawable(drawable)
photoView.minimumScale = 1f
photoView.maximumScale = 30f
```

**Comment by BigBadaboom** [comment]
The drawables you create with `newPictureDrawable(svg.renderToPicture())` should zoom just fine.  Is it possible that it is PhotoView at fault?

Can you post a sample app that loads an SVG into PhotoView so I can see the problem?

Another possibility is the SVG you are using. For example, if it contained a bitmap image, that would obviously not stay smooth when it gets scaled up.

**Comment by BigBadaboom** [comment]
Closing this old issue, due to lack of response.
