### ISSUE TITLE
What's the plan? :)

### ISSUE THREAD

**Issue by AdityaAnand1** [BigBadaboom/androidsvg#132]
Hi there! I'd just like to thank you for all the work you put in this library. Using this, I was able to make one of the most popular [icon maker](https://play.google.com/store/apps/details?id=xeus.iconic) apps on Android :)

In fact, I've been using a privately "modded" version of this library since ~3 years. So I was pleasantly surprised when I saw the [commit graph](https://github.com/BigBadaboom/androidsvg/graphs/contributors) rising up again!

So, I was just wondering, what's the plan? Android has had first class vector support for quite a while now, but it's not the same as SVG. Are you planning anything new for the library? Maybe take a look at those long standing issues? I could lend a hand 😄

**Comment by BigBadaboom** [comment]
I'm working towards a 1.3 release. See the [items remaining for 1.3](https://github.com/BigBadaboom/androidsvg/milestones).

I hope to push a 1.3 beta release to the Maven Repository in the next few days so people can start testing it.
