### ISSUE TITLE
is android:src Mandatory in xml? and uri from internet not supported?

### ISSUE THREAD

**Issue by suarezu** [BigBadaboom/androidsvg#134]
Hi, I have two questions, 1st is:

`<ConstraintLayout...>
<com.caverock.androidsvg.SVGImageView
        android:id="@+id/svg"
        android:layout_width="200dp"
        android:layout_height="200dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</ConstraintLayout>
`
this code generated an **Error inflating class com.caverock.androidsvg.SVGImageView**

I want to add the image view in xml and later to specify its svg source in code, and I think this use case is more general since the source maybe comes from internet which needs to be dynamically set after the app is run.

The 2nd question, after investigating the decompiled source code, is it seems the setImageUri(...) does not support uri of **http://...** format? I think this is another general requirement.

**Comment by suarezu** [comment]
on version 1.3, the first question is resolved, but the second question remains, and the error is reported as: 
E/SVGImageView: File not found: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/accessible.svg

**Comment by BigBadaboom** [comment]
No. Internet URLs are not supported.  It needs to be a resource in your app.  If you want to support SVGs from a URL, you need to fetch the file yourself, parse it with one of the `SVG.getFromX()` methods, then update the `SVGImageView` by calling `setSVG()`.

**Comment by suarezu** [comment]
Thank you Big, if so, I will try a custom and flexible drawable which accepts a layer list of SVGs, any of which can be of input stream of internet source retrieved by SVG.getFromInputStream().

**Comment by suarezu** [comment]
Big, another question irrelative to the title, any way to set alpha of a SVG?

**Comment by suarezu** [comment]
I have already done with SVGDrawable, it accepts both string-formatted and url-connected SVGs and multiple layers added and a default drawable to be rendered when no SVG at all, I can push it back if you need it as an enhancement to the existing library.

**Comment by BigBadaboom** [comment]
If you mean of the whole `SVGImageView`, then yes.  You can use either of the two methods:

- `android:alpha="0.5"
- `mySvgImageView.setAlpha(0.5f)` (or `setImageAlpha()`)

**Comment by suarezu** [comment]
No, I didnt mean the ImageView, I meant the SVG itself when rendering

**Comment by BigBadaboom** [comment]
The `opacity` attribute is supported, so you could do:

    <svg ... opacity="0.5" ...>

Or the equivalent CSS in a `<style>` element or `style=""` attribute.

Or if you are directly rendering to a Canvas, you could use `saveLayerAlpha()`. Ie.:

    canvas.saveLayerAlpha(null, 128);
    SVG.renderToCanvas(...);
    canvas.restore();

Or if you wait a bit, you'll be able to pass extra CSS in when you render.  This is one of the things I am putting into 1.3.

**Comment by suarezu** [comment]
Thank you very much, Big, you are so helpful, I made it by `canvas.saveLayerAlpha(null, 128);`

**Comment by BigBadaboom** [comment]
You're welcome.
