### ISSUE TITLE
PreserveAspectRatio doesnt work

### ISSUE THREAD

**Issue by suarezu** [BigBadaboom/androidsvg#135]
Hi, Big, I come back again, since when I render the SVG to canvas, no matter whichever PreserveAspectRatio I set to the SVG, the render result remains the same. I have also searched the issues and tried below before rendering:
`svg.setDocumentWidth("100%");
            svg.setDocumentHeight("100%");
            svg.setDocumentPreserveAspectRatio(PreserveAspectRatio.LETTERBOX);`

and also I found you said it's a bug due to android and this issue cant be resolved by you alone. Am I right? There is still no solution to this issue? The content of my svg file follows:
`<?xml version="1.0"?>
                    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1024" height="768"><rect x="10" y="10" rx="10" ry="10" width="492" height="718" fill="#DDDDDD" fill-opacity="1" /><rect x="512" y="10" rx="10" ry="10" width="492" height="718" fill="#DDDDDD" fill-opacity="1" /><rect x="20" y="20" rx="10" ry="10" width="200" height="100" fill="#C0C0C0" fill-opacity="1" /><rect x="20" y="130" rx="10" ry="10" width="200" height="100" fill="#C0C0C0" fill-opacity="1" /><rect x="20" y="240" rx="10" ry="10" width="200" height="100" fill="#C0C0C0" fill-opacity="1" /><rect x="20" y="350" rx="10" ry="10" width="200" height="100" fill="#C0C0C0" fill-opacity="1" /><rect x="20" y="460" rx="10" ry="10" width="200" height="100" fill="#C0C0C0" fill-opacity="1" /><rect x="230" y="20" rx="10" ry="10" width="200" height="100" fill="#C0C0C0" fill-opacity="1" /><rect x="230" y="130" rx="10" ry="10" width="200" height="100" fill="#C0C0C0" fill-opacity="1" /><rect x="230" y="240" rx="10" ry="10" width="200" height="100" fill="#C0C0C0" fill-opacity="1" /><rect x="230" y="350" rx="10" ry="10" width="200" height="100" fill="#C0C0C0" fill-opacity="1" /><rect x="230" y="460" rx="10" ry="10" width="200" height="100" fill="#C0C0C0" fill-opacity="1" /></svg>`

**Comment by BigBadaboom** [comment]
Hi

For `preserveAspectRatio` to work, the SVG must have a `viewBox`  It is the `viewBox` that tells the renderer what the dimensions of the SVG content are.  Without that, it has no way of knowing how much scaling needs to be applied.  Try adding something like:

    svg.setDocumentViewBox(0, 0, 1024, 768);

http://bigbadaboom.github.io/androidsvg/faq.html#My_SVG_won't_scale_to_fit_the_canvas_or_my_ImageView

**Comment by BigBadaboom** [comment]
I'm glad things are now working for you.
