### ISSUE TITLE
Possibility to scale SVG to bigger image size

### ISSUE THREAD

**Issue by kenobasedow** [BigBadaboom/androidsvg#138]
I am rendering an svg with this header:

`<svg version="1.2"  baseProfile="tiny" xmlns:svg="http://www.w3.org/2000/svg"
	 xmlns="http://www.w3.org/2000/svg"
	 x="0" y="0" width="0.42917in" height="0.0971in" viewBox="0 0 42.917 9.71" `

With 96 DPI this calculates to 41.2 x 9.3 pixels. I want to render the svg to an image view with 1080 x 1536 pixel in fullscreen. Now the SVG is shown very small. I haven't found a way to scale the SVG.
Would it be possible to add a method to effect the viewPort argument of the renderDocument method?

**Comment by kenobasedow** [comment]
My Intention is to read SVG that are not from me. Is it possible to scale from the library without changing the SVG?

**Comment by BigBadaboom** [comment]
Yes. You can do:
```
svg.setDocumentWidth("100%");
svg.setDocumentHeight("100%");
```

See the documentation: http://bigbadaboom.github.io/androidsvg/api_summary.html
Or the JavaDoc: http://bigbadaboom.github.io/androidsvg/doc/reference/com/caverock/androidsvg/SVG.html

There is also a [FAQ question on this topic](http://bigbadaboom.github.io/androidsvg/faq.html#My_document_has_a_viewBox,_but_it_is_still_not_scaling)

**Comment by kenobasedow** [comment]
OK, thank you. I try it out.

**Comment by BigBadaboom** [comment]
You're welcome.
