### ISSUE TITLE
I'm getting images to have a greenish texture background on all images

### ISSUE THREAD

**Issue by balsikandar** [BigBadaboom/androidsvg#139]
![capture](https://user-images.githubusercontent.com/13173447/40159192-b91e7bbc-59c5-11e8-83ad-c5d1704824b9.PNG)

**Comment by balsikandar** [comment]
I further checked basically `cls-1{fill:fff;}` was used for carBody which for some reason looks greenish after rendering. So i changed it to `cls-1{fill:none;}` it looks fine now. So my problem is solved but greenish texture could be an issue for someone else

**Comment by BigBadaboom** [comment]
Thanks for your report.

Can you post the SVG please?  I won't be able to investigate this issue without an example to test with.

**Comment by balsikandar** [comment]
SVG isn't supported so i converted it to txt. 

[bodytype_Hatchback.txt](https://github.com/BigBadaboom/androidsvg/files/2017675/bodytype_Hatchback.txt)

**Comment by BigBadaboom** [comment]
The SVG you attached works for me. But I notice it is a different image. It's a hatchback instead of a minivan.  Did you attach the wrong file?

**Comment by balsikandar** [comment]
I have been having issues with this one as well. I used this exact code with the given SVG and i got the issue

`// Read an SVG from the assets folder
SVG  svg = SVG.getFromAsset(getContext().getAssets(), filename);

// Create a canvas to draw onto
if (svg.getDocumentWidth() != -1) {
   Bitmap  newBM = Bitmap.createBitmap((int) Math.ceil(svg.getDocumentWidth()),
                                       (int) Math.ceil(svg.getDocumentHeight()),
                                       Bitmap.Config.ARGB_8888);
   Canvas  bmcanvas = new Canvas(newBM);

   // Clear background to white
   bmcanvas.drawRGB(255, 255, 255);

   // Render our document onto our canvas
   svg.renderToCanvas(bmcanvas);
}`

Does this works good for you?

**Comment by BigBadaboom** [comment]
Ah yes. That explains it.  There was a bug in the parsing of short colours that has since been fixed.  The fix will be in the next release (1.3). You can read about that release and how to test it here:

http://bigbadaboom.github.io/androidsvg/release-1.3.html

If you are using your own clone of the repo, the [patch required to fix this is here](https://github.com/BigBadaboom/androidsvg/pull/103/commits/49465a2e8abd4faab7d66d29c44ca553f3b54e4f)

**Comment by balsikandar** [comment]
Thanks my issue is fixed by tweaking SVG and will upgrade as soon as v1.3 is released to remove any manual labour
