### ISSUE TITLE
SVG always renders to the viewBox size

### ISSUE THREAD

**Issue by paour** [BigBadaboom/androidsvg#143]
I'm using the library (both the latest release and the 1.3 snapshot) to render [an SVG](https://lls-media-public.s3-eu-west-1.amazonaws.com/histoire-3e-2016/la-seconde-guerre-mondiale/un-centre-de-mise-a-mort-treblinka/h.3.3.loc1..svg) to a 3000x3000 bitmap (wrapped in a Canvas), but regardless of the options I set (forcing width, height, preserveAspectRatio=letterbox), what I get is a big bitmap with the SVG rendered in a corner.

Is this because my SVG is incompatible, or am I missing an option to allow the renderer to scale to use the full size of the bitmap?

**Comment by paour** [comment]
Oops, sorry I missed that FAQ! That is indeed the situation, but I can't change the document. Is there a way to override this behavior?

**Comment by BigBadaboom** [comment]
Yes. You can use the code in the FAQ answer.  It doesn't change your original document. Right now, it only changes AndroidSVG's internal representation of the document.

Another thing you could do is set the Canvas's transformation matrix before you render the SVG.

    mycanvas.save();
    mycanvas.scale(10f, 10f);
    mysvg.renderToCanvas(mycanvas);
    mycanvas.restore();

or, for example, you could do:

    mycanvas.save();
    mycanvas.scale(3000f/mysvg.getDocumentWidth(), 3000f/mysvg.getDocumentHeight());
    mysvg.renderToCanvas(mycanvas);
    mycanvas.restore();

(as long as the SVGs always have `width` and `height` attributes.

**Comment by paour** [comment]
Thank you for your kind assistance @BigBadaboom. After more careful analysis on my part, the issue was that the SVGs were lacking a `viewBox`. This is why forcing the width and height was not having any effect. I ended up having to regenerate the `viewBox` based on the width and height to resolve the issue. Kraken was used to optimize the files, and for some reason it seems to have discarded this important data.

**Comment by BigBadaboom** [comment]
Ah!  Glad you solved the problem.  Good luck with your project.
