### ISSUE TITLE
SVGParser is not threadsafe: Stuck in corrupted HashMap.get() when parsing multiple SVGs simultaneously

### ISSUE THREAD

**Issue by brudaswen** [BigBadaboom/androidsvg#145]
Parsing multiple SVGs simultaneously can cause some threads to block entirely. The issue is caused by corrupted HashMaps when updating the cache of `SVGElem` and `SVGAttr`.

I will provide a PR shortly.

Thanks a lot for your work!

**Comment by BigBadaboom** [comment]
Thanks for the patch Sven.  Much appreciated!
