### ISSUE TITLE
Render not correct if preserveAspectRatio is "xMinYMin meet"

### ISSUE THREAD

**Issue by gene7299** [BigBadaboom/androidsvg#159]
When I use the SVG as follows, the result of rendering between Chrome & this androidsvg on Android is different. The image rendered by androidsvg is smaller the rendered by Chrome.
How to fixed that?

Thanks.

```

<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="159.835" height="329.899" viewBox="43.593 96.8658 5.3738995 32.3715" preserveAspectRatio="xMinYMin meet">
<path d="M44.593 97.8658 L47.9668 128.237" style="fill:none; stroke:#000000; stroke-width:0.238125pt"/></svg>


```

**Comment by BigBadaboom** [comment]
Hi. Thanks for your report.

Can you elaborate on what you mean please?  Smaller how?  Can you provide some screen shots please?  How are you rendering the SVG?  Are you using SVGImageView?  Or some other method?

**Comment by gene7299** [comment]
Sorry, It's my fault. It's look like rendering is correctly. Thanks for your reply.

**Comment by BigBadaboom** [comment]
Ok. Glad you got your problem sorted out.
