### ISSUE TITLE
 can't find referenced method 'int save(int)' in library class android.graphics.Canvas

### ISSUE THREAD

**Issue by Visotskiy** [BigBadaboom/androidsvg#160]
After update sdk on 28 version we have this error - can't find referenced method 'int save(int)' in library class android.graphics.Canvas

Method Canvas.save(int) has been removed from Android SDK (API 28)

**Comment by BigBadaboom** [comment]
Which version of AndroidSVG are you using?  This should be fixed in v1.3.

**Comment by BigBadaboom** [comment]
I'm going to mark this as a dup of #148 for now.  If that is not the case, and instead you think you have found a new bug, please let me know and I will reopen it.
