### ISSUE TITLE
SVG pixelated when rendered to canvas

### ISSUE THREAD

**Issue by fazjaxton** [BigBadaboom/androidsvg#162]
I am loading my file as follows:

    AssetManager m = getContext().getAssets();
    SVG mSvg = SVG.getFromAsset(m, filename);

In onDraw:

    mSvg.renderToCanvas(c)  // Also tried specifying a rectF

In both the one- and two- argument render-to-canvas calls, the image appears pixelated, as though it was rendered to a smaller image and scaled up.  Am I using the API wrong?  Here is the SVG I am testing with: [Emoji Face](https://github.com/twitter/twemoji/blob/gh-pages/svg/1f600.svg)

**Comment by BigBadaboom** [comment]
This is likely a dup of #165.  The issue being a fault with hardware rendering of scaled paths on pre-Pie devices. 

I'm going to close this now on the assumption that I am correct.  If you are still seeing this issue when running on a Pie device or emulator, please let me know and I will reopen this issue.

Thanks
