### ISSUE TITLE
SVG renderToPicture not working with Oreo

### ISSUE THREAD

**Issue by initiuminc1** [BigBadaboom/androidsvg#163]
I have the issue with devices above oreo. Working well with the other devices

**Comment by BigBadaboom** [comment]
Thanks for your report.  Do you have any other information?  Do you get any errors?

**Comment by initiuminc1** [comment]
Not getting any specific errors. instead of that getting an empty white screen. The same code works well on M

**Comment by BigBadaboom** [comment]
Can you provide a sample of code?  Or perhaps a test project or APK?

**Comment by BigBadaboom** [comment]
Cannot reproduce.

Closing for now. If you can provide an example that fails, please update the issue and I will reopen it.
