### ISSUE TITLE
Android 9 canvas.saveLayer is removed

### ISSUE THREAD

**Issue by hungyanbin** [BigBadaboom/androidsvg#164]
Since API level 26, the api saveLayerAlpha(@Nullable RectF bounds, int alpha, @Saveflags int saveFlags) and saveLayer(@Nullable RectF bounds, @Nullable Paint paint, @Saveflags int saveFlags) is deprecated, and it is removed at API level 28.

This library still using api with saveFlags, see [SVGAndroidRenderer](https://github.com/BigBadaboom/androidsvg/blob/0d1614dd1a4da10ea4afe3b0cea1361a4ac6b45a/androidsvg/src/main/java/com/caverock/androidsvg/SVGAndroidRenderer.java) line 727. If using this library run on Android 9 devices, It will cause our app crash.

**Comment by BigBadaboom** [comment]
Thanks for your report.

`saveLayerAlpha(RectF, int)` has been deprecated in API 28, but has not been removed as yet.  It should not cause a crash as long as we are using `Canvas.ALL_SAVE_FLAG` for the flags.  Which is the case.

**Comment by BigBadaboom** [comment]
Fixed.  I've added some future-proofing in case this method gets suddenly removed form a future Android release.
