### ISSUE TITLE
Support `isolation` and `mix-blend-mode` CSS properties

### ISSUE THREAD

**Issue by BigBadaboom** [BigBadaboom/androidsvg#168]
This should be quite straightforward tom implement on Android Q due to the new `BlendModeColorFilter` class.

https://drafts.fxtf.org/compositing-1/#csskeywords
https://developer.android.com/reference/android/graphics/BlendModeColorFilter

**Comment by BigBadaboom** [comment]
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <g style="isolation:isolate">
    <circle cx="50" cy="50" r="40" fill="#ff74b6"/>
    <g style="mix-blend-mode:color-burn">
      <rect y="20" width="100" height="30" fill="#d1d3d4"/>
    </g>
  </g>
</svg>

```

**Comment by formariz** [comment]
Hi @BigBadaboom 
Have any news about the `mix-blend-mode` support?

**Comment by BigBadaboom** [comment]
I hadn't prioritized it very high because the required support is new in Android 10.

But since it has a couple of hearts, I'll bump it up a little. :)

**Comment by i-mitra** [comment]
Hi @BigBadaboom, really appreciate all the work you put into this library. Blending modes is one of the most requested feature by our designers to showcase their content on our application. Do you have any timeline for this issue? I'd like to help you with this issue, if possible?

**Comment by BigBadaboom** [comment]
I believe I will finally have some time to work on the backlog of
outstanding issues for version 1.5 of AndroidSVG in the next week or two.

Thanks for your interest.
Paul

**Comment by BigBadaboom** [comment]
Done.
