### ISSUE TITLE
Change CSS for fill with color

### ISSUE THREAD

**Issue by mamodo123** [BigBadaboom/androidsvg#169]
hello. setColorFilter doesn't work, so i want to fill wall my SVGImage with a color, using css. how? i'm trying:

img.setSVG(mySvg, "path { fill: blue; }");

**Comment by BigBadaboom** [comment]
Hi

If that isn't working then a possible reason is that your paths use `style="fill: whatever"`.   The `style` attribute overrides CSS and the `fill` attribute.  You would need to modify your SVG to remove the `fill` from the `style` attribute.

If that isn't the reason, then I would probably need to see your SVG.

**Comment by BigBadaboom** [comment]
Unfortunately, I don't upport !important yet. Otherwise that would have worked.

What you can try instead is make your CSS selectors more specific. They should then have greater precendence than the rules in your SVG file.

    img.setSVG(mySvg, "path.a, ellipse.b, path.c, path.d, path.e, path.f { fill: blue; }");

**Comment by mamodo123** [comment]
oh, ok! please implement teh `!important` haha.

**Comment by BigBadaboom** [comment]
Did my last suggestion work for you?  If so, I will close this issue.
