### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by ShaMan123** [BigBadaboom/androidsvg#172]
I tried testing this repo as a native dependency of `react-native`.
Responsiveness degraded extremely.
Frames are dropped by the thousands and the UI thread operates on near 0 fps and doesn't recover, however rendering is spotless.
Any suggestions or ideas why this is happening?
Is there a lot of work done on the UI thread that can be done on different threads?

**Comment by BigBadaboom** [comment]
Hi.
AndroidSVG will do its work on whichever thread you call the `renderToX()` methods on.  I'm not sure what else it could do.

Perhaps if you provide more information about how you are using the library, I can provide more information.  Are you rendering SVGs yourself? Or are you using SVGImageView?

**Comment by ShaMan123** [comment]
Excellent! Thanks. I was rendering myself overriding `onDraw`. Switched to `SVGImageView` and it's blazing fast!

**Comment by BigBadaboom** [comment]
Thanks. I'm glad your issue is solved.

It's usually the parsing that takes the most time.  SVGImageView does the parsing on a separate thread. You could also do it that way yourself, if you really wanted to use onDraw().

**Comment by ShaMan123** [comment]
Now I have a different issue.
I think it's to do with `react-native` stuff but maybe you could suggest a direction.
I will open a new ticket
