### ISSUE TITLE
Remove unnecessary org.jetbrains:annotations-java5 dependency

### ISSUE THREAD

**Issue by ashughes** [BigBadaboom/androidsvg#173]
I ran into an issue when updating to Android Gradle Plugin 3.4.1 from 3.3.2 (see https://issuetracker.google.com/issues/133216058). I determined that the conflicting annotations were due to the `org.jetbrains:annotations-java5` dependency in this project: https://github.com/BigBadaboom/androidsvg/blob/3707369974a672b6c7de28dd11f5728d973fe1d0/androidsvg/build.gradle#L31

As far as I can tell, this dependency is unnecessary and should be removed.

**Comment by BigBadaboom** [comment]
Thanks for the report.  This is now fixed.
