### ISSUE TITLE
<image> with href link not working

### ISSUE THREAD

**Issue by anuragkyalsc** [BigBadaboom/androidsvg#174]
Tried to render the below SVG. As you can see from the screenshot, the image is missing from the output. Seems like this is not listed in the not supported features. A bug?

```
<svg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg' width="400" height="400">
    <g id="comicSvg">
        <text id="font-size-indicator-1" x="5" y="30" style="font-size: 24px; fill: red;">42</text>
        <text id="font-size-indicator-2" x="5" y="50" style="font-size: 24px; fill: red;"></text>
        <rect id="canvasbox" x="0" y="0" width="398" height="398" style="stroke: lightgrey; stroke-width: 2; fill: none;"></rect>
        <image x="0" y="0" width="398" height="398" href="https://www.w3schools.com/howto/img_forest.jpg"></image>
        <rect id="bindingbox" x="0" y="0" width="398" height="398" style="stroke: green; stroke-width: 2; fill: none; stroke-dasharray: 5,5"></rect>
    </g>
</svg>
```

Just using the sample app and modified `RenderToImageFragment` to read my svg file.

Output:

<img width=200 src="https://user-images.githubusercontent.com/16907712/58354308-06955480-7e3f-11e9-8632-5681790a7998.png">

**Comment by BigBadaboom** [comment]
Hi

By default, AndroidSVG won't fetch images from URLs when rendering `<image>` tags.  In fact it doesn't know how to fetch any type of external resource (including images, fonts, CSS etc).  You need to fetch those for it.

You do that using an instance of `SVGExternalFileResolver`.  If you want it to fetch from an external website, you'll need to write an implementation of that interface that does an HTTP fetch and returns the decoded image.

Most people don't want to do that though.  If that image isn't going to change, then you should copy it into your `assets` folder.  AndroidSVG comes with an external file resolver implementation, called  `SimpleAssetResolver` designed to fetch files from the `assets` folder.

You use it by making the following call before you try to load the SVG:

    SVG.registerExternalFileResolver(new SimpleAssetResolver(getContext().getAssets()));

Hope this helps.

**Comment by BigBadaboom** [comment]
Hopefully this explains your problem.  If it doesn't, please comment and I will reopen the issue.

**Comment by mhernand40** [comment]
>By default, AndroidSVG won't fetch images from URLs when rendering <image> tags. In fact it doesn't know how to fetch any type of external resource (including images, fonts, CSS etc). You need to fetch those for it.

Is it safe to assume that this also applies to an `href` that is set to Base64-encoded Data URI?
Example:
```SVG
<svg width="100%" height="100%" viewBox="0 0 1200 1200" version="1.2" xmlns="http://www.w3.org/2000/svg">
  <image width="1200" height="1200" href="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTI...=="></image>
</svg>
```

**Comment by BigBadaboom** [comment]
@mhernand40  No. That should work.  Try using `xlink:href="..."` instead though.
