### ISSUE TITLE
How do I calculate an SVG path's bounding box?

### ISSUE THREAD

**Issue by romanzes** [BigBadaboom/androidsvg#179]
Is it possible to calculate the bounding box of an SVG path with this library?
I see `PathConverter` and `calculatePathBounds()` inside `SVGAndroidRenderer`, but they are private...

**Comment by BigBadaboom** [comment]
Do you mean that you want to pass in a path definition (eg. "M 0,0 L 100,50...etc...") and get the bounding box for it?  If so, then no, we don't currently support that.

If you would like to make a feature request to be able to pass in a path definition and get an Android `Path` object back, then I could look at adding that feature.  You could then call `computeBounds()` on that `Path` object.

**Comment by romanzes** [comment]
>Do you mean that you want to pass in a path definition (eg. "M 0,0 L 100,50...etc...") and get the bounding box for it?

Yes, that's exactly what I meant! Would be very nice to have this feature.

**Comment by BigBadaboom** [comment]
There was already an issue for this request: #14 (although it got accidentally closed some time ago).

Watch that bug for updates.

**Comment by romanzes** [comment]
@BigBadaboom sorry, I don't see how #14 is related to this issue. Perhaps you meant some other issue?

**Comment by BigBadaboom** [comment]
Sorry. Typo. I meant #41.
