### ISSUE TITLE
stroke-width is missinterpreted

### ISSUE THREAD

**Issue by olimaticer** [BigBadaboom/androidsvg#185]
AndroidSvg will be part of the Basic Interpreter for Android **OliBasic**
as a fork based on the RFO-Basic
https://www.tapatalk.com/groups/rfobasic/hot-summer-of-code-t4408.html#p31251

The atribut **stroke-width** is missinterpreted.
```
<?xml version="1.0" standalone="no"?>
<svg width="5cm" height="4cm" version="1.1"
     xmlns="http://www.w3.org/2000/svg">
    <rect x="0.5cm" y="0.5cm" width="2cm" height="1cm"/>
    <rect x="0.5cm" y="2cm" width="1cm" height="1.5cm" fill="red"/>
    <rect x="3cm" y="0.5cm" width="1.5cm" height="2cm"/>
    <rect x="3.5cm" y="3cm" width="1cm" height="0.5cm"/>

  <!-- Show outline of viewport using 'rect' element -->
  <rect x=".1cm" y=".1cm" width="4.8cm" height="3.8cm" fill="none" 
stroke="green" stroke-opacity="0.2" stroke-width="0.1cm" />

</svg>
```
![Screenshot_20191119-230432](https://user-images.githubusercontent.com/5593376/69196032-a0f3fd80-0b2d-11ea-853a-233b84c106c5.png)

Get this result if stroke-width="0.1cm" is deleted, changed into stroke-width="4.8cm" or width="4.8cm" is moved to the end of the line.
vvvvvvvvvvv
![Screenshot_20191119-230537](https://user-images.githubusercontent.com/5593376/69196548-1d3b1080-0b2f-11ea-919d-041ceaf024c6.png)

Get this message from androidvsg from **2014**
vvvvvvvvvvv
![Screenshot_20191119-225732](https://user-images.githubusercontent.com/5593376/69195903-422e8400-0b2d-11ea-9c5b-7b972fae133f.png)

```
  <!-- Show outline of viewport using 'rect' element -->
  <rect x=".1cm" y=".1cm" width="4.8cm" height="3.8cm" style="fill:none;stroke-width:0.1cm;stroke:green;stroke-opacity:0.2" />
```

do it right

![Screenshot_20191120-013514](https://user-images.githubusercontent.com/5593376/69198784-3bf0d580-0b36-11ea-9860-5902b6453390.png)

It seems a closed Style-atribut-range is missed.
Perhaps set each identified atribut between characters like this "€width€".

"€width€" and "€stroke€" should not be part of "€stroke-width€"

Many thanks for this lib!!

**Comment by olimaticer** [comment]
"€width€" should not be part of "€stroke-width€"

**Comment by BigBadaboom** [comment]
I tried your SVG file.  The current version of AndroidSVG renders it correctly.  Which version are you using?

**Comment by olimaticer** [comment]
Two days ago the source directly here from GitHub.
File dates are all the 2019-10-26.

**Comment by BigBadaboom** [comment]
Perhaps I misinterpreted your bug report wrong.  I just tested the first SVG you posted.  Was that one failing?

If not, could you just post a sample SVG that doesn't work for you please?

**Comment by olimaticer** [comment]
I am very sorry. My fault.
A fix for the old version had survived.
Thank you very much for your quick response.
The issue can be closed.

**Comment by BigBadaboom** [comment]
No worries.  I would much rather get false bug reports than none at all. ;)
Good luck with your project.
