### ISSUE TITLE
Parsing Issue in Case of param:;

### ISSUE THREAD

**Issue by olimaticer** [BigBadaboom/androidsvg#186]
Example 

`<text x='105' y='150' transform='rotate(45 105 150)' style='font-family:arial;font-size:8;font-weight:normal;font-style:normal;text-decoration:§§§;text-anchor:middle;stroke:rgba(0,0,255,1.0);stroke-width:0.3;fill:none;GRshape-rendering:crispEdges'>Print this drawing from (Chrome) Browser</text>`

§§§ for text-decoration: is wrong and will be ignored, ;text-anchor:middle; ;stroke:rgba(0,0,255,1.0) and later will be executed correctly.

Is §§§ instead an empty string ;text-anchor:middle; ;stroke:rgba(0,0,255,1.0) and later will be ignored also.
It seems the parser try in this case to interpret text-anchor as a value, middle as variable name and so on.

[Downloads.zip](https://github.com/BigBadaboom/androidsvg/files/3888871/Downloads.zip)

Where can I fix this?

Gregor

**Comment by BigBadaboom** [comment]
HI Thanks for the report.

Are you saying that `text-annchor...etc` is parsed when it shouldn't be, or not parsed when it should be?  I can't tell from your description.

**Comment by olimaticer** [comment]
It will be parsed, if the value is a right one. In this case it returns the wished value.
It will be parsed, if the value is a false one, the default value will be returned.
It will be not parsed, if the string for interpretation of the value is an empty string, this and all following items returns only the defaults.

Or shorter, the parser stumble over **":;"** after the style tag.

**Comment by BigBadaboom** [comment]
Fixed.  Improved style attribute parsing.
