### ISSUE TITLE
Get in Trouble with Sizing, ViewBox especially by Negative Viewpoints Like -X and -Y

### ISSUE THREAD

**Issue by olimaticer** [BigBadaboom/androidsvg#187]
Hi Paul

**Case (1)**
My intent is to load SVG graphcis and convert them into bitmaps in original size perhaps in 96 DPI relation.
**Case (2)**
Create a bitmap in given borders to maintain the original relationship between width and height.
**Case (3)**
Create a bitmap like case 2 but crop a part from the source referenced by the original size
and a view point of **X=0** and **Y=0**.

The common SVG editor **Inkscape** is a little special, because it uses sometimes negative view points. (Zeichnung.svg)
How can I crop if the view point is different from X=0 and Y=0 in this case?

I have tried a little by got no full success.

```
   public static Bitmap getSvgFromString (String svgText, Bundle svgParams) throws Exception {
   	Bitmap  newBM=null;
		int[] cArray = Tools.parseColorError(svgParams.getString("bgColor", ""));
		int bgColor = cArray[0];
		if (cArray[1] == 1){
			bgColor = 0; //Error
		}
		int mfp = svgParams.getInt("mfp");
		
		float left = svgParams.getFloat("left");
		float top = svgParams.getFloat("top");
		float cropwidth = svgParams.getFloat("cropwidth");
		float cropheigth = svgParams.getFloat("cropheigth");

		// vv Parameters to change or delete in the original SVG header
		int startSvgH = svgText.indexOf("<svg") + 4;
		int endSvgH = svgText.indexOf(">", startSvgH);
		String svgTextTopHeader = svgText.substring(0, startSvgH);
		String svgTextHeader = svgText.substring(startSvgH, endSvgH);
		String svgTextMain = svgText.substring(endSvgH);
		//Run.PrintShow(svgTextTopHeader + "§"+ svgTextHeader + "§"+ svgTextMain);
		String[] toDel = {"preserveAspectRatio"};
		Float mWidth = 0f;
		Float mHeight = 0f;
		Float vbX = 0f;
		Float vbY = 0f;
		Float vbWidth = 0f;
		Float vbHeight = 0f;
		String sC = "\'";
		String dC = "\"";
		if (svgTextHeader.indexOf(dC) > -1 )sC = dC;
		String newHeader = " ";
		boolean isViewBox = false;
		if (svgTextHeader.toLowerCase().indexOf("viewbox=")> -1)isViewBox = true;
		String[] elements = svgTextHeader.split(sC);
		for (int i = 0; i < elements.length; i++){
			if (elements[i].indexOf("=") > -1){
				elements[i] = elements[i].replace(" ","");
				boolean del = false;
				for (String search : toDel){
					if (elements[i].toLowerCase().indexOf((search.toLowerCase() + "="))> -1)del = true;
				}
				if (elements[i].toLowerCase().indexOf(("width" + "="))> -1)
					mWidth = Float.valueOf(elements[i+1].replaceAll("[A-Za-z]", ""));
				if (elements[i].toLowerCase().indexOf(("height" + "="))> -1)
					mHeight = Float.valueOf(elements[i+1].replaceAll("[A-Za-z]", ""));
				if (elements[i].toLowerCase().indexOf(("viewbox" + "="))> -1){
					String[] members = elements[i+1].replaceAll("  ", " ").split(" ");
					vbX = Float.valueOf(members[0]);
					vbY = Float.valueOf(members[1]);
					vbWidth = Float.valueOf(members[2]);
					vbHeight = Float.valueOf(members[3]);
				}
				if (!del)newHeader += elements[i] + sC + elements[i+1] + sC + " ";
				if (!isViewBox && mWidth > 0 && mHeight > 0 ){
			//		newHeader += "viewBox="+ sC +  "0 0 "+ mWidth + " " + mHeight + sC + " ";
					isViewBox = true;
				}
			}
		}
		// Run.PrintShow("viewbox: \n" + vbX + ", " + vbY + "\n" + vbWidth + ", " + vbHeight);
		// Run.PrintShow("Sizes: \n" + mWidth + ", " + mHeight);
		
		// Run.PrintShow("newHeader: \n" + newHeader);
		svgText = svgTextTopHeader + newHeader + svgTextMain;
		svgTextMain = null;
		// ^^ Parameters to delete in the SVG header

		SVG svg = null;
		svg = SVG.getFromString(svgText);
 		if (svg.getDocumentWidth() != -1) {
 			boolean autoIcon = false ;
 			if (autoIcon == true){
	  			//DisplayMetrics dm = new DisplayMetrics();
	 			//getWindowManager().getDefaultDisplay().getMetrics(dm);
	 			//int density = dm.densityDpi;
				/*
 				int size = (int)Math.ceil(48 * density / 160); //160 is the reference density.
 				svg.setDocumentWidth( size);
	        	svg.setDocumentHeight( size);
	        	newBM = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
	        	*/
 			}else{
	  			float svw = svg.getDocumentWidth();
	  			float svh = svg.getDocumentHeight();
	  			RectF  viewBoxRect = svg.getDocumentViewBox();
	  			// If no ViewBox create, one.
	  			if (viewBoxRect == null)svg.setDocumentViewBox(0, 0, svw, svh);
	  			viewBoxRect = svg.getDocumentViewBox();
/*
 				// Option  ifViewPointNegative
	  			if (viewBoxRect.left < 0)svg.setDocumentViewBox(0, viewBoxRect.top, svw, viewBoxRect.bottom-viewBoxRect.top);
	  			if (viewBoxRect.top < 0)svg.setDocumentViewBox(viewBoxRect.left, 0, viewBoxRect.right-viewBoxRect.left, svh);
	  			if (viewBoxRect.left < 0 && viewBoxRect.top > 0)svg.setDocumentViewBox(viewBoxRect.left, viewBoxRect.top, 
	  					viewBoxRect.right-viewBoxRect.top, viewBoxRect.bottom-viewBoxRect.top);
	  			Float Sum = viewBoxRect.left + viewBoxRect.top + viewBoxRect.right + viewBoxRect.bottom;
	  			Run.PrintShow(" : " + viewBoxRect.toString());
*/
	  			
 				int lbw = svgParams.getInt("width");
 				int lbh = svgParams.getInt("height");
 				if (mfp > 0 ){		//MemoryFaultPrevention / 2013-09-27 gt || (lbw == 0 && lbh == 0 )
 					if (left+top+cropwidth+cropheigth != 0 ){
 						// To crop create a ViewBox
 	 					// *** Case (3) ***
 						if (cropwidth == -1 || (left + cropwidth) > svw)cropwidth = svw - left;
 						if (cropheigth == -1 || (top + cropheigth) > svh)cropheigth = svh - top;
 						svg.setDocumentViewBox(left+viewBoxRect.left, top+viewBoxRect.top, cropwidth, cropheigth);
 					}else{
 						// Load the full image in wished borders but do not create a missed ViewBox
 	 					// *** Case (2) ***
 						cropwidth = svw;
 						cropheigth = svh;
 					}
 					// { // Keep care that the right size is returned in given borders
					double ar = 1;
	        		if (lbw > 0 || lbh > 0)
	        			ar = Math.min( (double) lbw/cropwidth,(double) lbh/cropheigth);
	        		if ((lbw == 0 && lbh > 0)||(lbw > 0 && lbh == 0))
	        			ar = Math.max( (double) lbw/cropwidth,(double) lbh/cropheigth);
	        	 	svg.setDocumentWidth( (int) fix(cropwidth*ar));
	        	 	svg.setDocumentHeight( (int) fix(cropheigth*ar));
	        	 	// }
	        	 	newBM = Bitmap.createBitmap((int) fix(cropwidth*ar), (int) fix(cropheigth*ar), Bitmap.Config.ARGB_8888);

 				}else {
 					// Load the SVG by 96 DPI
 					// *** Case (1) ***
       			newBM = Bitmap.createBitmap((int) fix(svw), (int) fix(svh), Bitmap.Config.ARGB_8888);
 				}
 			}
 			// Create a canvas to draw onto
 			Canvas  bmcanvas = new Canvas(newBM);
 			// Clear background to color
 			// bmcanvas.drawRGB(255, 255, 255);
 			if (bgColor != 0)bmcanvas.drawColor(bgColor);
 			
			// Render our document onto our canvas
 			svg.renderToCanvas(bmcanvas);
 		}	
    return newBM;
   }
```

[SVGs.zip](https://github.com/BigBadaboom/androidsvg/files/3889077/SVGs.zip)
[svgTest ifViewPointNegative.zip](https://github.com/BigBadaboom/androidsvg/files/3889078/svgTest.ifViewPointNegative.zip)
[svgTest preserve§§§AspectRatio.zip](https://github.com/BigBadaboom/androidsvg/files/3889079/svgTest.preserve.AspectRatio.zip)
[svgTest preserveAspectRatio.zip](https://github.com/BigBadaboom/androidsvg/files/3889080/svgTest.preserveAspectRatio.zip)

Gregor

**Comment by BigBadaboom** [comment]
Hi Gregor

I'm not quite clear on what you want to do.  It sounds like you want to

(a) scale the SVG to fit a particular image size (calculated based on screen density)
(b) generate a second bitmap at the original size with a "viewpoint" of 0, 0.

Is that correct?

When you say "viewpoint", do you mean that the SVG coordinate (0,0) should be at the centre of the bitmap.

Can you describe what you are actually ultimately trying to achieve?  What is the problem with your SVGs that you are trying to solve?  It sounds a little like you got stuck trying to solve a problem in a particular way.  Perhaps there is a simpler approach I can suggest that you weren't aware of.

**Comment by olimaticer** [comment]
(a) scale the SVG to fit to particular maximum given image size borderes
(b) crop a second bitmap from the original with a "viewpoint" of 0, 0 and original scale. Now scale the returned result to fit to particular maximum given image size borderes.

![HowToCrop](https://user-images.githubusercontent.com/5593376/69682955-6fda7680-10b3-11ea-9d99-776de7ae1473.png)

The Question is where and how (pt, %, em) to scale the dimensions into pixel.

Gregor

**Comment by BigBadaboom** [comment]
Ok. Thatshould be quite simple.  I'll respond with some code shortly.

But I have one question: in the second example, the60x90 crop area is positioned on the left of the 90x90 viewport.  How is that determined?  Should the code do that for all input SVGs?

**Comment by BigBadaboom** [comment]
You shouldn't need to mess around with the SVG as much as you are doing.  SVGs are designed to automatically scale to fit your viewport.  And AndroidSVG supports that.

```
// Case 2 - scale the SVG to fit a bittmap
// Note: assumes the SVG has a viewBox

SVG svg = SVG.getFromString(svgText);

// Setting width and height to 100% tells the renderer to scale to fill the viewport
svg.setDocumentWidth("100%");
svg.setDocumentHeight("100%");

int size = 454;   // Whatever size you want for the bitmap
caseTwoBM = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
caseTwoCanvas = new Canvas(caseTwoBM);
svg.renderToCanvas(caseTwoCanvas);

// Case 3 - focus on a particular region of the SVG specified by
// 'left', 'top', 'cropwidth' and 'cropheight'

if (cropwidth > 0 && cropheigth > 0 ) {
   svg.setDocumentViewBox(left, top, cropwidth, cropheight);

   // Your example pushes the object to the left edge. You can do that with:
   // preserveAspectRatio="xMinYMid meet"
   PreservAspectRatio p = new PreserveAspectRatio(PreserveAspectRatio.Alignment.XMinYMid,
                                                  PreserveAspectRatio.Scale.Meet);
   svg.setDocumentPreserveAspectRatio(p);

   int size2 = 90;  // or whatever
   caseThreeBM = Bitmap.createBitmap(size2, size2, Bitmap.Config.ARGB_8888);
   caseThreeCanvas = new Canvas(caseThreeBM);
   svg.renderToCanvas(caseThreeCanvas);
}
```

If I have understood your needs correctly, then that is all that should be needed.

**Comment by olimaticer** [comment]
Hi Paul

```
// Setting width and height to 100% tells the renderer to scale to fill the viewport
svg.setDocumentWidth("100%");
svg.setDocumentHeight("100%");
```
does the trick in Case 1 and 2

```
  // Your example pushes the object to the left edge. You can do that with:
   // preserveAspectRatio="xMinYMid meet"
   PreservAspectRatio p = new PreserveAspectRatio(PreserveAspectRatio.Alignment.XMinYMid,
                                                  PreserveAspectRatio.Scale.Meet);
   svg.setDocumentPreserveAspectRatio(p);
```
has no effect.
Is it right, that I had to set  PreservAspectRatio  and setDocumentPreserveAspectRatio in SVG.java to public?

With
`svg.setDocumentViewBox(left, top, cropwidth, cropheight);`
I have a problem, because it needs pixels.
But in reality it needs values in the original dimension for example mm.
So I have to convert from pixel into mm by deviding with 3.78 (96/25.4).
I have tried to detect the dimension by parsing the svg header.
That is normally successful but in cat.svg the header is in mm and the values are in pixels.
Any ideas?
Could you deliver
`svg.setDocumentViewBox("0%", "10%", "100%", "90%");`
?

**Comment by BigBadaboom** [comment]
> Is it right, that I had to set PreservAspectRatio and setDocumentPreserveAspectRatio in SVG.java to public?

They are already public.

> I have a problem, because by default it needs pixels, but in reality it needs values in the original dimension for example mm.  So I have to convert from pixel into mm...

I don't undertsand why you have to convert into mm.  Can you please explain?

> Could you deliver `svg.setDocumentViewBox("0%", "10%", "100%", "90%");`

What would these percentages represent?  10% of what?

**Comment by olimaticer** [comment]
> I don't undertsand why you have to convert into mm. Can you please explain?

From **Drawing2.svg** width='210mm' height='297mm' viewBox='0 0 210 297'
If I use svg.setDocumentViewBox(0,0,794,1123), I get a wrong result.
svg.setDocumentViewBox(0,0,210,297) is ok.

> > Could you deliver svg.setDocumentViewBox("0%", "10%", "100%", "90%");
> 
> What would these percentages represent? 10% of what?

10 % of svg.setDocumentHeight("100%");
Because in **cat.svg**'s svg header width="36.52mm" and height="49.02mm", but in the main part
in pixel. In **Drawing2.svg** width='210mm' and height='297mm', but in the main part in mm.

If I insert in **cat.svg** viewBox='0 0 36.52 49.02' it fails, but
viewBox='0 0 138 185' is ok
Personally I have a lot of files like cat.svg.

Perhaps name it svg.setDocument**CropBoxFromWhole**("0%", "10%", "100%", "90%");

Gregor

**Comment by BigBadaboom** [comment]
The units for the new viewBox have to be in the SVG coordinate space.  Ie. the same space as the originat viewBox is defined in.  Using mm values based on the original `width` and `height` is incorrect.

Imagine your crop rectangle is an actual rectangle in the file.  What would the coordinate attributes of that rectangle be?  Those are the values you should use for the new viewBox.

> 10 % of svg.setDocumentHeight("100%");

You could calculate those values yourself. For example: `viewBox.x + 10% * viewBox.width`.

**Comment by olimaticer** [comment]
Paul

I had to drill a thick board.
Thank you very much.
```

 		float faktW = left/svw;
 		float faktH = top/svh;
 		float faktWc = cropwidth/svw;
 		float faktHc = cropheight/svh;
 		svg.setDocumentViewBox(viewBoxRect.left + faktW*viewBoxRect.width(), 
 				viewBoxRect.top + faktH*viewBoxRect.height(), 
 				faktWc*viewBoxRect.width(), faktHc*viewBoxRect.height());
 		svg.setDocumentWidth("100%");
 		svg.setDocumentHeight("100%");
```
Now it is dimension independent and I can allow persentages as input also.

BTW removing preserveAspectRatio from the svg header is needed. (Drawing*.svg)


Gregor

**Comment by BigBadaboom** [comment]
> BTW removing preserveAspectRatio from the svg header is needed. (Drawing*.svg)

You can set it to the default (equivalent to removing it) with:

    PreservAspectRatio p = new PreserveAspectRatio(PreserveAspectRatio.Alignment.XMidYMid,
                                                   PreserveAspectRatio.Scale.Meet);
    svg.setDocumentPreserveAspectRatio(p);

I'm glad you resolved your problem.  Thanks for using AndroidSVG.

Paul
