### ISSUE TITLE
SVG failing to parse

### ISSUE THREAD

**Issue by NickG123** [BigBadaboom/androidsvg#189]
Hi There,
I have an SVG that is failing to parse in this library.  When I run `SVG.getFromInputStream` it results in the error `SVGParseException invalid document. Root element must be <svg>`.  The SVG appears to be a valid SVG, and I haven't had any issues with other applications parsing it.
Please see attached for the SVG in question.
Thanks,
Nick
[world.zip](https://github.com/BigBadaboom/androidsvg/files/4199416/world.zip)

**Comment by BigBadaboom** [comment]
Fixed issue with parsing of unknown elements.
Parsing was not correct if an unknown element contained a element with the same tag name as a valid SVG element.

**Comment by NickG123** [comment]
Awesome! Thanks for the quick response!

**Comment by BigBadaboom** [comment]
No problem! Thanks for the bug report.

**Comment by NickG123** [comment]
Hi there, just wondering if you know when you'll be able to make a new release? We'd like to integrate these changes into our project 😄
