### ISSUE TITLE
"New" XML parsing doesn't work on API 10

### ISSUE THREAD

**Issue by TWiStErRob** [BigBadaboom/androidsvg#193]
Caused by #122 
AndroidSVG Version: 1.4

There are two problems:
On API 10 the pull parser throws an exception:
```
    java.lang.UnsupportedOperationException
        at org.apache.harmony.xml.ExpatPullParser.nextToken(ExpatPullParser.java:311)
        at com.caverock.androidsvg.SVGParser.parseUsingXmlPullParser(SVGParser.java:754)
        at com.caverock.androidsvg.SVGParser.parse(SVGParser.java:603)
        at com.caverock.androidsvg.SVG.getFromInputStream(SVG.java:150)
        at net.twisterrob.android.content.glide.SvgBitmapDecoder.decode(SvgBitmapDecoder.java:42)
```
so what I asked for in https://github.com/BigBadaboom/androidsvg/issues/122#issuecomment-466830295 is relevant again. If I could change the parser to always use the standard Java one, it would be nice, or if it was automatically done via an `SDK_INT` decision, even better :)

I was curious if simply using the old parser would work, so I "simulated" it:
```java
private SVG getFromInputStream_and_SVGParser_parse(InputStream source) throws Exception {
	Class<?> SVGParser = Class.forName("com.caverock.androidsvg.SVGParser");
	Constructor<?> ctor = SVGParser.getDeclaredConstructor();
	ctor.setAccessible(true); // default visible class
	Object parser = ctor.newInstance();
	Field svgDocument = SVGParser.getDeclaredField("svgDocument");
	svgDocument.setAccessible(true); // private field
	Method parseUsingSAX = SVGParser.getDeclaredMethod("parseUsingSAX", InputStream.class);
	parseUsingSAX.setAccessible(true); // private method
	parseUsingSAX.invoke(parser, source);
	return (SVG)svgDocument.get(parser);
}
```
this worked fine to skip the new parser, however it still failed:
```
javax.xml.parsers.ParserConfigurationException: org.xml.sax.SAXNotRecognizedException: http://xml.org/sax/features/external-parameter-entities
    at com.caverock.androidsvg.SVGParser.parseUsingSAX(SVGParser.java:798)
	... 25 more
```
at this point I went even further and simulated `parseUsingSAX` without `setFeature` calls:
```java
private SVG getFromInputStream_and_SVGParser_parse(InputStream source) throws Exception {
	Class<?> SVGParser = Class.forName("com.caverock.androidsvg.SVGParser");
	Constructor<?> ctor = SVGParser.getDeclaredConstructor();
	ctor.setAccessible(true);
	Object parser = ctor.newInstance();
	Field svgDocument = SVGParser.getDeclaredField("svgDocument");
	svgDocument.setAccessible(true);
	parseUsingSAX(parser, source);
	return (SVG)svgDocument.get(parser);
}

private void parseUsingSAX(Object parser, InputStream is) throws Exception {
	SAXParserFactory spf = SAXParserFactory.newInstance();

	//spf.setFeature("http://xml.org/sax/features/external-general-entities", false);
	//spf.setFeature("http://xml.org/sax/features/external-parameter-entities", false);

	SAXParser sp = spf.newSAXParser();
	XMLReader xr = sp.getXMLReader();

	Class<?> SAXHandler = Class.forName("com.caverock.androidsvg.SVGParser$SAXHandler");
	Constructor<?> ctor = SAXHandler.getDeclaredConstructor(parser.getClass());
	ctor.setAccessible(true); // private inner class
	ContentHandler handler = (ContentHandler)ctor.newInstance(parser);
	xr.setContentHandler(handler);
	xr.setProperty("http://xml.org/sax/properties/lexical-handler", handler);

	xr.parse(new InputSource(is));
}
```
and voilà, it works on all my files perfectly on API 10.

## Suggested solution
So there's an issue with using `parseUsingXmlPullParser` on API 10, API 15 works. So somewhere between 10 and 15 they added support for external entities. Which means there needs to be an `SDK_INT` condition to use `parseUsingSAX` when `< 15`. (I think 14 would support it too as 15 is a patch release of 14.)

Additionally the `setFeature` lines need to be only applied when they're supported. So either catch `ParserConfigurationException` and retry `newSAXParser()` without setting the features, or put the `setFeature` calls in an `SDK_INT` condition too. I tried it on API 15 and it works with your production version + when I forced `parseUsingSAX` with `setFeature`, it also works on API 15.

So adding two `VERSION_CODES.ICE_CREAM_SANDWICH <= VERSION.SDK_INT` conditions to use the new features, makes it work on all platforms I could test. These conditions should be regardless of `enableInternalEntities`.

**Comment by TWiStErRob** [comment]
Note: I think this `catch` can easily cause a double-parse of the stream:
https://github.com/BigBadaboom/androidsvg/blob/ef779a3c0fcbf1ee84fed67ccede111803d870b0/androidsvg/src/main/java/com/caverock/androidsvg/SVGParser.java#L623
because `parseUsingXmlPullParser` is inside `try`, and if that fails, the catch calls `parseUsingXmlPullParser` again.

**Comment by BigBadaboom** [comment]
Thanks for catching the API issue Rob.  I'll take a look.

The `try`/`catch` thing shouldn't be an issue.  The `catch` is on an `IOException`, but `parseUsingXmlPullParser()` throws an `SVGParseException` (`SAXException`).

**Comment by BigBadaboom** [comment]
Fixed.

Thanks vm Robert for the report and investigation.
