### ISSUE TITLE
Rendering of text-anchor="middle" wrong in case of a very small font size

### ISSUE THREAD

**Issue by vesselink** [BigBadaboom/androidsvg#195]
The font size in the attached svg is super small (0.06) so measureText is unusable.
Will add a pull request with a proposal to fix the issue.

[FastStart_Autocad.zip](https://github.com/BigBadaboom/androidsvg/files/4604462/FastStart_Autocad.zip)

**Comment by BigBadaboom** [comment]
Thanks very much! I'll make sure this gets merged into the next release.

**Comment by BigBadaboom** [comment]
Fixed.

Fix for right and center alignment of text with very small font sizes.  Android's Paint.measureText() returns widths that are too large because it rounds up fractional results.  Thanks to @vesselink for the fix!
