### ISSUE TITLE
fill-opacity not properly rendered

### ISSUE THREAD

**Issue by ewaldc** [BigBadaboom/androidsvg#198]
The attached svg (uploaded as text file) does not render the pattern with the requested fill opacity of 0.2.
It is my understanding from the documentation that _fill-opacity_ is supported as part of the style attributes. Also tried with percentages (20% vs 0.2) , but it makes no difference.
It renders properly on several browsers (Chrome, MS Edge, Firefox) as well as several online viewers/editors. 
AndroidSVG Version: 1.4
[chart_opacity.txt](https://github.com/BigBadaboom/androidsvg/files/4678514/chart_opacity.txt)

Haven't looked at the source code to figure out where the issue might be...
Don't know if there is somewhere an online SVG viewer using this library so I can test what works and what not. 
Thanks in advance

**Comment by BigBadaboom** [comment]
Hi. Thanks for the report, and example file.  I'll take a look.

**Comment by ewaldc** [comment]
I have been able to narrow the problem down to _setPaintColour_ in SVGAndroidRenderer.java as follows:
- _paintOpacity_ is correctly set to 0.2
- _paint_ however is a href ("pattern1") and thus not an instance of SVG.Colour nor SVG.CurrentColor
- hence the functions returns @line 2428 and _colourWithOpacity_ is never called

I think the code should also proceed when paint is an instance of _PaintReference_
I'll make the code change and see if I can get it to work and drop a diff/patch.

**Comment by ewaldc** [comment]
It seems fixing that part is not sufficient.  This piece of code seems to support gradient and solid pattern fills as part of a style reference but **NOT patterns** e.g. _fill: url(#id):_
SVGAndroidRenderer.java: _decodePaintReference()_ @ 3317
```
      if (ref instanceof SvgLinearGradient)
         makeLinearGradient(isFill, boundingBox, (SvgLinearGradient) ref);
      else if (ref instanceof SvgRadialGradient)
         makeRadialGradient(isFill, boundingBox, (SvgRadialGradient) ref);
      else if (ref instanceof SolidColor)
         setSolidColor(isFill, (SolidColor) ref);
      //if (ref instanceof SVG.Pattern) {}  // May be needed later if/when we do direct rendering
```
Yet, the pattern is rendered (see grid in screenshot), just not with the requested gradient...
More analysis needed...
![Screenshot_20200528-134232_openHAB_Beta](https://user-images.githubusercontent.com/14278196/83293316-e899c700-a1eb-11ea-878e-40ba84cefa84.png)

**Comment by BigBadaboom** [comment]
Fixed.

Thanks for the report.
