### ISSUE TITLE
SVG.registerExternalFileResolver API is not thread safe

### ISSUE THREAD

**Issue by maniac103** [BigBadaboom/androidsvg#199]
In our app, we download SVGs via HTTP and render them to bitmaps. Those images are fetched not only from one HTTP server, but from multiple servers, where each download + conversion is done in different thread. This poses a problem for the aforementioned API due to its singleton nature, since the (one) registered resolver doesn't know what HTTP server to talk to when trying to resolve an included file, as there's no context about the operation passed in.

My suggestion on a changed API would be either
- (optionally) passing a resolver instance to the SVG.getFrom* methods, which would then be preferred over the static one, or
- (optionally) passing an opaque context object to those methods, which then later is passed to the resolver methods or
- allow passing an resolver instance into an SVGParser instance so that that one is used during parsing (that way, we could use the parser class directly instead of the convenience methods) ... using that route would require making the SVGParser class public

**Comment by maniac103** [comment]
After thinking about this a bit more, I think the third suggestion is the most elegant one, as it keeps backwards compatibility. What I'd do would be
- Create a public SVGParser interface with setters for the various parser properties that have static setters in the SVG class plus a `SVG parse(InputStream stream)` method
- Rename existing SVGParser to SVGParserImpl, inheriting from the interface
- Add a static `SVGParser createParser()` method to the SVG class
- That method creates an SVGParserImpl instance and calls the setters mentioned above with the values from the static setters in SVG class
- Convert the various get from* methods to use createParser
- The parser inherits the attributes set on it to the parsed SVG
- When all this is done, the static attributes (e.g. the resolver instance) in the SVG class should be private to that class and not be used elsewhere
- For existing users nothing should change, only behavioral change would be changes to the static properties not being inherited by SVGs parsed before that point, but I don't think that's a supported use case.

What do you think of that proposal? I can look into implementing it if you're OK with it.

**Comment by BigBadaboom** [comment]
Hi.  That sounds like a good approach to me.

If you do create a PR that implements that approach, I will be happy to merge it.
