### ISSUE TITLE
Cyrillic letters in style definitions are not recognized

### ISSUE THREAD

**Issue by mlshf** [BigBadaboom/androidsvg#204]
Your project is an amazing help for the app I am currently developing!

However, there is a slight issue with Cyrillic letters used in style class definitions. As soon as parser encounters Cyrillic - all further styles are ignored. 

I of course can work around this by simply translating class names to English on the server side. Yet it would definitely be helpful to be able to use Cyrillic in SVG to increase readability for Russian users of your project.

I will attach an example of the styles definition section to illustrate the issue. 
[styleDefExample.txt](https://github.com/BigBadaboom/androidsvg/files/4877904/styleDefExample.txt)

Parser will understand "black" and "white" styles but upon parsing "голубойМГТ" this style and all styles further will be ignored, even those that are written in English, like "red" or "stopPlaceCodeFont".

**Comment by BigBadaboom** [comment]
Thanks for the report.  I agree this needs to be fixed.

Note to myself: [CSS Selectors Level 3](https://www.w3.org/TR/css-syntax-3/#typedef-ident-token)

**Comment by BigBadaboom** [comment]
Fixed.

Added support for  for non-ASCII chars (those >= U+0080) in CSS class names.
