### ISSUE TITLE
NullPointerException when points attribute is missing in polyline/polygon elements.

### ISSUE THREAD

**Issue by cbukenya** [BigBadaboom/androidsvg#205]
An exception thrown java.lang.NullPointerException: Attempt to get length of null array
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1367)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:375)
	at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:395)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:649)
	at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:328)
	at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:603)
	at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:557)

**Comment by cbukenya** [comment]
I am using version 1.4. Unfortunately I don't have a specific file, its a signature that is created on a canvass that I am trying to render. Below is a snippet of my code.
`/**
     * Extracts and coverts signature image data from workflow data and saves it to local storage so
     * that integration to read it.
     */
    @Nullable
    public Uri convertSvgToJpgAndGetUri(ProofOfDelivery pod, String fileNameWithExtension) {

        Uri uri = null;

        if (pod != null) {

            String signatureSvg = pod.getSignature();

            if (signatureSvg != null) {
                try {
                    //svg input file
                    InputStream inputStream = new ByteArrayInputStream(
                            signatureSvg.getBytes(StandardCharsets.UTF_8));
                    SVG svg = SVG.getFromInputStream(inputStream);

                    if (svg.getDocumentWidth() != -1) {
                        Bitmap bitmap = Bitmap.createBitmap((int) Math.ceil(svg.getDocumentWidth()),
                                (int) Math.ceil(svg.getDocumentHeight()),
                                Bitmap.Config.ARGB_8888);

                        Canvas bmcanvas = new Canvas(bitmap);
                        bmcanvas.drawRGB(255, 255, 255);
                        svg.renderToCanvas(bmcanvas);

                        //jpg output file
                        File path = context.getExternalFilesDir(null);
                        File outputFile = new File(path, fileNameWithExtension);
                        OutputStream fileOutputStream = new FileOutputStream(outputFile);

                        bitmap.compress(Bitmap.CompressFormat.JPEG, 10, fileOutputStream);

                        fileOutputStream.flush();
                        fileOutputStream.close();
                        uri = Uri.fromFile(outputFile);
                    }
                } catch (SVGParseException | IOException e) {
                    _log.error(TAG, "Exception: " + e);
                }
            }
        }

        return uri;
    }`

**Comment by BigBadaboom** [comment]
Hi.

Are you sure it's release 1.4?  Are you using the .aar file?  If I checkout that release and compare lines with the stacktrace, they don't match the code.  Did you perhaps build your own library from a different source revision?

Paul

**Comment by cbukenya** [comment]
Hi, yes I was running the 1.4v when I got this issue several times. But as I was trying to debug this issue, I downloaded the source from here from the master branch and run it directly in my android app as a module so I can debug it. That's when I copied the log above, so that is why the  lines may not be exactly as 1.4 release version.

**Comment by BigBadaboom** [comment]
Ok great. That helps.  Do you know what date you fetched the code?  I've been making a lot of changes in the last couple of weeks.

**Comment by cbukenya** [comment]
Sep 21

**Comment by cbukenya** [comment]
[
![image_2021-01-28_212135](https://user-images.githubusercontent.com/46421174/106194193-cd35f000-61ae-11eb-93f6-9f3a8cdb0acf.png)

**Comment by cbukenya** [comment]
I fixed this by doing this and I dont get the crush anymore. Added lib directly to my source, but could be nice to fix it here

**Comment by BigBadaboom** [comment]
Fixed bugs relating to empty or missing points attribute in <polyline> and <polygon> elements.

**Comment by BigBadaboom** [comment]
@cbukenya Thanks for finding the cause of the fault.  That was very useful.

**Comment by stephentalley** [comment]
We're running into this same bug in our app. Is there a reason it hasn't made its way into a release? It looks like there hasn't been a release in 3 years, despite man commits to the repo...

**Comment by BigBadaboom** [comment]
@stephentalley Sorry about that.  I plan to release v1.5 soon.
