### ISSUE TITLE
support SVGImageView clear

### ISSUE THREAD

**Issue by jiyewushen** [BigBadaboom/androidsvg#208]
SVGImageView will use old cache and did't refresh like the following example.
use SVGImageView in RecyclerView,  item has called setImageAsset() and the file can find ,however,if file not found when reuse this item, item did't refresh.

**Comment by BigBadaboom** [comment]
@jiyewushen Sorry this hasn't been looked at yet.  Is this still a bug?  If so, I will reopen this.

Can you make it clearer what the sequence of events is?

Is it:
- setImageAsset() with availeable image -> displays ok
- setImageAsset() with missing image - still displays last image
Is that correct?

What do you think should happen?  A blank image view?
