### ISSUE TITLE
UnsupportedOperationException in v1.3 and android api level < 11

### ISSUE THREAD

**Issue by lekanteto** [BigBadaboom/androidsvg#210]
In version 1.3:
eventType = parser.nextToken(); in SVGParser throws an UnsupportedOperationException on Android api level < 11.

I tried to change the parser to "XmlPullParserFactory.newInstance().newPullParser()" but then I get an "unsupported feature: http://xmlpull.org/v1/doc/features.html#process-docdecl (position:START_DOCUMENT null@0:0)" exception.

I cannot use v1.4 because I need to support api level 10 devices.

**Comment by lekanteto** [comment]
Ups.... my bad. It looks like I mixed up v1.4 and "current" where I saw minSdk of 14.
So I can use v1.4 and I am happy :-)

Sorry for the confusion.

**Comment by BigBadaboom** [comment]
No worries.

BTW the current version is not going to stay at 14.  I've already reset it back to 10 in my local fork.
