### ISSUE TITLE
Null Pointer Exception at com.caverock.androidsvg.SVG$SvgViewBoxContainer.viewBox

### ISSUE THREAD

**Issue by FahadSaleem** [BigBadaboom/androidsvg#211]
Hi, I have the following SVG file (Halloween-21.svg) that crashes when you assign it using `svgImageView.setImageUri()` but does not crash when you assign it using `svgImageView.setImageAsset()`

Some how, passing it as URI gives the following error: 

![image](https://user-images.githubusercontent.com/21174438/103857156-be8c7980-50d7-11eb-8ca2-fea37bc302b1.png)

I have attached both the SVG file and the project (the SVG file can be found in the assets of this project, goes by the name of Halloween-21). 

Please make sure to add this file to the downloads folder of your device/emulator first and give permissions. 

Attaching drive link because zip was > 10 MB. https://drive.google.com/file/d/1g-r59T0TBiicEcOB9RXhKeweKuCVeCvP/view?usp=sharing

**Comment by BigBadaboom** [comment]
Thanks for the bug report.  I will check this out.

**Comment by FahadSaleem** [comment]
NP. Do you have any estimated time until this gets fixed?

**Comment by BigBadaboom** [comment]
@FahadSaleem Hi. 

I was able to successfully read and display the file when I put it in the app-specific Download folder (`/storage/emulated/0/Android/data/com.example.svgviewboxcrashapp/files/Download`).

But when I try via `/storage/emulated/0/Download`, the app can't even read it (File not found).  Does the crash only happen when it is in that folder?

What was your method for setting the permissions on that file?  What permissions does it need?  My understanding is that you can't change file permissions in that part of the file system.  Do I need a rooted device for this?

I tried emulators running API 26, 29, and 30, to test whether it's related to the changes to storage/emulated in API 29.  But all had the same result (File not found).

Can you provide a little more information please?

Thanks
Paul

**Comment by BigBadaboom** [comment]
Closing this old bug due to lack of response.  I am going to assume it is no longer a problem.  Let me know if it still is, and I will be happy to reopen.
