### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.StringBuilder.toString()' on a null object reference         at com.caverock.androidsvg.SVGParser.endElement(SVGParser.java:798)

### ISSUE THREAD

**Issue by catkbm** [BigBadaboom/androidsvg#212]
Some SVG images are not parsing correctly, getting that issue. Thanks in advance

**Comment by catkbm** [comment]
Some SVG images are not parsing correctly, getting that issue. Thanks in advance

**Comment by BigBadaboom** [comment]
Hi. Thanks for the report.

- Which version of the library are you using? The 1.4 release, the latest dev branch, or something else?
- Can you provide a test file that triggers this error please?  

This might be the same problem as Issue #177, but they were not able to provide a test file, so I ended up closing the bug.

**Comment by lystyp** [comment]
I meet with the same problem, 

gradle : 
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    implementation 'com.caverock:androidsvg:1.2.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

svg url : 
http://www.svgrepo.com/show/382174/book-education-learning-puzzle-school-study.svg

**Comment by BigBadaboom** [comment]
@lystyp Thanks for the update. I tried your file also and had no issues rendering it.

**Comment by BigBadaboom** [comment]
No response from original reporter. So I'm reluctantly closing this issue. I'm going to assume that OP was using an old version of
