### ISSUE TITLE
svg problem

### ISSUE THREAD

**Issue by Rahmahry** [BigBadaboom/androidsvg#213]
.
Hello. I'm sorry but i have little bit of a problem.  

                  final URL url = new URL(url);
                    HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();
                    InputStream inputStream = urlConnection.getInputStream();
                    SVG svg = SVG.getFromInputStream(inputStream);
                    bitmap = Bitmap.createBitmap((int) Math.ceil(svg.getDocumentWidth()),
                            (int) Math.ceil(svg.getDocumentHeight()),
                            Bitmap.Config.ARGB_8888);
                    Canvas canvas = new Canvas(bitmap);
                    svg.renderToCanvas(canvas);

It returns low image quality. How to fix it?
A svg image has low resolution (It's very little) but it's svg. It must be good.
If i use phone with big resolution then image has low quality but it's svg. It must be good.
Any methods to parse svg to get good quality for all resolutions?
Sorry for my bad Ensglish

**Comment by BigBadaboom** [comment]
Hi Rahmahry

You possibly don't want to be using `getDocumentWidth()` and `getDocumentHeight()`.  What those values are will depend on what the `width` and `height` attributes are in you SVG.

What are you doing with the Bitmap once you have rendered the SVG to it?  It would help to know that in order to give you the best advice.

It would also help to see the SVG you are using.

Paul

**Comment by BigBadaboom** [comment]
Hi

Check this FAQ entry, and see if it solves your problem.

[My SVG doesn't render if I try to do Canvas.drawPicture()](https://bigbadaboom.github.io/androidsvg/faq.html#My_SVG_doesn't_render_if_I_try_to_do_Canvas.drawPicture()_o)

----

Your SVG has hardwired width and hight values: `   width="52.258327mm" height="60.303696mm"`.  That corresponds to 
about 198 x 228px.  That's pretty small.  Try overriding those values:

```
SVG svg = SVG.getFromInputStream(inputStream);
svg.setDocumentWidth("100%");
svg.setDocumentHeight("100%");
drawable = new PictureDrawable(svg.renderToPicture())   // or renderToCanvas() either whould work
```

[More information here](https://bigbadaboom.github.io/androidsvg/faq.html#My_SVG_won't_scale_to_fit_the_canvas_or_my_ImageView)

**Comment by BigBadaboom** [comment]
Closing this old issue.
