### ISSUE TITLE
character entities such as & disappear from texts.

### ISSUE THREAD

**Issue by NoeHedde** [BigBadaboom/androidsvg#214]
in text elements, using any character entities (ex. \&#x3C;) or special entities (\&lt;) does not work.

I have looked at the code and the issue is in the SVGParser where in the while loop, any event of type XmlPullParser.ENTITY_REF is ignored. this result in the disappearance of the "&" characters in the resulting SVG objects.

In the official SVGPull Parser doc https://developers.google.com/j2objc/javadoc/android/reference/org/xmlpull/v1/XmlPullParser.html#nextToken()

ENTITY_REF
getText() MUST return entity replacement text if PROCESS_DOCDECL is false otherwise getText() MAY return null, additionally getTextCharacters() MUST return entity name (for example 'entity_name' for &entity_name;). 
NOTE: this is the only place where value returned from getText() and getTextCharacters() are different 
NOTE: it is user responsibility to resolve entity reference if PROCESS_DOCDECL is false and there is no entity replacement text set in defineEntityReplacementText() method (getText() will be null) 
NOTE: character entities (ex. \&#x3C;) and standard entities such as \&amp; \&lt; \&gt; \&quot; \&apos; are reported as well and are not reported as TEXT tokens but as ENTITY_REF tokens! This requirement is added to allow to do roundtrip of XML documents!

**Comment by BigBadaboom** [comment]
Fixed.  Forgot to close.
