### ISSUE TITLE
Can This library trace the Text into paths?

### ISSUE THREAD

**Issue by Egorkansk** [BigBadaboom/androidsvg#239]
Can This library trace the Text into paths?

**Comment by BigBadaboom** [comment]
No it doesn't have that feature.  However Android itself has an API for that.

Take a look at the [`Paint.getTextPath()` methods](https://developer.android.com/reference/android/graphics/Paint#getTextPath(char[],%20int,%20int,%20float,%20float,%20android.graphics.Path)).
