### ISSUE TITLE
SVG.getfromString(?)

### ISSUE THREAD

**Issue by Egorkansk** [BigBadaboom/androidsvg#242]
please write me working sample what I can type in String parameter of this function? I tryed to type svg data but I have svgparseexseption

**Comment by BigBadaboom** [comment]
Can you post an example SVG that fails for you. And the full stacktrace for the exception.

If an SVG works elsewhere, it should work with `getFromString()` also.

**Comment by act262** [comment]
it should be full string 

`
<svg viewBox="0, 0, 224, 126" preserveAspectRatio="xMidYMid meet" id="mask" xmlns="http://www.w3.org/2000/svg"><defs><filter id="f1" x="0" y="0"><feGaussianBlur in="SourceGraphic" stdDeviation="1"/></filter></defs><g filter="url(#f1)" fill="#000" stroke="none"><path fill-rule="evenodd" d="M0,0 0,125 93,125 92,120 93,116 94,112 95,108 96,104 98,101 98,99 101,93 103,90 106,87 106,85 108,82 117,73 119,71 120,68 123,64 128,59 134,54 134,51 133,49 131,46 129,44 126,41 126,28 127,23 129,19 131,16 134,12 136,10 139,8 142,7 146,6 148,6 152,8 154,10 157,11 159,13 161,15 164,18 165,20 166,24 167,28 167,39 166,43 164,46 163,49 163,55 169,61 178,69 180,70 183,71 185,71 188,72 191,73 193,74 199,80 204,86 206,90 207,94 207,96 212,105 213,109 213,113 214,116 216,119 216,125 223,125 223,0 "/></g></svg>
`

**Comment by BigBadaboom** [comment]
No response from OP. So I'm closing this now.
