### ISSUE TITLE
Incorrect svg rendering.

### ISSUE THREAD

**Issue by thejask** [BigBadaboom/androidsvg#249]
**Describe the bug**
It is noticed that some svg files are not rendered correctly on android device by COIL library. We tried with both v2.0.0 and v2.1.0. And same svg file renders fine on browser (Chrome and Mozilla). 

Note : Originally, this issue was reported at android COIL library github, but they suggested it to be reported here. [#1291](https://github.com/coil-kt/coil/issues/1291)

**To Reproduce**
- Load svg file via Coil-kt/COIL android image loading library.
[coil-kt/coil](https://github.com/coil-kt/coil)

**Expected behavior**
It should render correctly. 

**SVG file**
![share](https://user-images.githubusercontent.com/5175970/170363786-5ef603e0-0ad0-4db4-bf67-53ffd66d0951.svg)

**Screenshots**
![android_screenshot](https://user-images.githubusercontent.com/5175970/170364192-40060c32-b46a-4e59-b92c-89a02ff2b0cb.png)

**Additional context**
Note :  same svg file renders fine on browsers like Chrome and Mozilla. Using android COIL library version v2.1.0, v2.0.0

**Comment by BigBadaboom** [comment]
Interesting.  It's been a long time since I've had a path parsing/rendering bug.  Thanks for the report.

**Comment by BigBadaboom** [comment]
Fixed.

S/s and T/t path commands were not being handled correctly if they were preceded by a V/v or H/h command. The cause was due to the lastControlX/lastControlY variables not being updated correctly in the V/v/H/h command handling.

This fix will appear in the next release version (1.5).

**Comment by BigBadaboom** [comment]
@thejask Incidentally, did you realise that you are clipping the bottom of your icon?  The `height` should be `38` to include the whole of the bottom line.

**Comment by thejask** [comment]
Thanks @BigBadaboom.

**Comment by ggrell** [comment]
Thanks for the fix @BigBadaboom! 
![who's awesome](https://media.giphy.com/media/KvGkTDzBnY03m/giphy.gif)
