### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Arashvscode** [BigBadaboom/androidsvg#251]
Hello, how can I use the xml photo preview if you can send me the Java code?

**Comment by BigBadaboom** [comment]
AndroidSVG renders SVG, not photos.

Did you really mean "photos"?  Or is that a translation mistake?

**Comment by Arashvscode** [comment]
> 

No, I want to read the path of the image from the dictatorship of memory

**Comment by BigBadaboom** [comment]
I'm sorry, we seem to be having machine translation problems here.

Can you expand your question with more information, so I can get a better idea of what you are wanting to do?

Thanks
