### ISSUE TITLE
[Feature] SVG to vector drawable

### ISSUE THREAD

**Issue by HenryProject** [BigBadaboom/androidsvg#252]
It would be great if this amazing SVG library had the ability to convert SVG to Android Vector drawable (.xml). Thanks in advance.

**Comment by BigBadaboom** [comment]
Do you mean at runtime?  Or as a standalone app?

**Comment by HenryProject** [comment]
As a function in runtime to convert both SVG string and SVG file. I've already write a very simple app to parse SVG and convert into the xml but it only parse the path data and its attributes, and convert all shapes to path data, it needs more enhancement such as parse SVG groups and reduced transformation into the path data. So I just want to have this function in this libs.

**Comment by BigBadaboom** [comment]
So you want to read in an SVG file, convert it to a VectorDrawable XML file. But then do what?  Save it?  Render it?

- If save it, why does it need to be a runtime function?  Why not just create an offline tool.  Or use one of the existing ones?
- If render it, then (a) why not just use AndroidSVG to render it?, also (b) the last I checked, it wasn't possible to assign a dynamically created VD file to an ImageView at runtime.

I'm afraid I don't see the use case for this feature.  Can you explain?

**Comment by HenryProject** [comment]
When I say runtime I mean convert SVG to string xml , just like below sample. As you can see in this sample I've use AndroidSVG to view SVGs and it works great, so I wanted to AndroidSVG has ability to convert that SVG to vector drawable, however I've implement my own converter for this purpose. But I'd love to AndroidSVG has that ability. Thanks anyway.

Sample that I use AndroidSVG:
![easy gif1655641244677](https://user-images.githubusercontent.com/101605023/174481017-d1080dd0-5cee-4e85-98bb-f0fb90852e33.gif)

**Comment by BigBadaboom** [comment]
I see.  What do users of your app do with those VD files once they have been converted.  Surely they are only really useful when building a new app?  Android Studio already has the ability to convert from SVG built in.

I know some developers use other IDEs such as Xamarin/Mono to develop Android apps.  Wouldn't it be better to develop a converter plugin for Mono instead?

Anyway, thanks for the suggestion, but I think this feature is a little too specific a use case to support withing AndroidSVG itself.

**Comment by BigBadaboom** [comment]
Closing as Won't Fix.  I don't think this feature is a good match for the intended purpose of AndroidSVG.
