### ISSUE TITLE
How to show vector xml file?

### ISSUE THREAD

**Issue by Arashvscode** [BigBadaboom/androidsvg#253]
Hi, I wanted to know if your library has the ability to display Victor or xml photos from the file dictation path?  If you can send me a sample Java code, thank you

**Comment by BigBadaboom** [comment]
There is no method for loading an SVG directly from a `File` or path string. but you can load from an `InputStream` (see `SVG.getFromInputStream()`).  There are other `getFromX()` methods for loading files from resource directories, the assets folder, and from a string.

[AndroidSVG documentation](http://bigbadaboom.github.io/androidsvg/documentation.html)
[Javadoc](http://bigbadaboom.github.io/androidsvg/doc/index.html)

There is also a sample application that you might find useful to look at: https://github.com/BigBadaboom/androidsvgsampleapp

**Comment by BigBadaboom** [comment]
Closing. Hopefully my answer solved your problem.
