### ISSUE TITLE
will your library support OpenHarmony platform by JavaScript language?

### ISSUE THREAD

**Issue by CCuoGuo** [BigBadaboom/androidsvg#255]
I am developing an OpenHarmony application with JavaScript language which used your library, will your library support OpenHarmony platform by JavaScript language?If so, I want to contribute to the OpenHarmony build of this library.Expecte for your reply!

**Comment by BigBadaboom** [comment]
Hi

I have no plans to create a JS port for OpenHarmony at this time..
