### ISSUE TITLE
How to show vector image xml file?

### ISSUE THREAD

**Issue by Arashvscode** [BigBadaboom/androidsvg#258]
Hello, I wanted to know if your library has the ability to decode and display xml vector images. If it has this ability, please help me install it. If not, add this feature. Thank you.

**Comment by BigBadaboom** [comment]
What sort of vector image are you talking about?  My library renders SVG files, which are XML based.
If you mean another sort of XML file, such as Android VectorDrawable files, then the answer is no.  Sorry.
