### ISSUE TITLE
Request: Bad property values should generate warning rather than failing to parse

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#26]
```
If there is some attributes not supported, the SVG can't be shown.
Such as:  stroke-linecap="null" stroke-linejoin="null" 

If it possible for just ignore these attributes in text element?
```

Original issue reported on code.google.com by `BraveZ...@gmail.com` on 6 Jan 2014 at 7:15

**Comment by BigBadaboom** [comment]
Bad property values no longer throw an exception when parsing. They are now just ignored.
Fixed bug with fill-opacity not affecting gradients as it should.
Made pattern rendering should be a little faster now.
Functional IRI parsing is now a little more forgiving to match browser behaviour.

**Comment by BigBadaboom** [comment]
Issue tagged with SVG2 due to the fill-opacity change.
