### ISSUE TITLE
Find the length and width of the svg

### ISSUE THREAD

**Issue by Arashvscode** [BigBadaboom/androidsvg#261]
Hello, I use this code to display the length and width of the svg, but it does not work and produces 0 for me, can you help me?

```java
	public static void GetSvgImageFile(String input, ImageView img, TextView tv1) {
		
		try {
			
			File startDir = new File(input);
			FileInputStream fileInputStream = new FileInputStream(startDir);
			
			SVG svg = SVG.getFromInputStream(fileInputStream);
			Drawable drawable = new PictureDrawable(svg.renderToPicture());
			img.setImageDrawable(drawable);
		//	float b = svg.getDocumentHeight();
		//	float c = svg.getDocumentWidth();
			tv1.setText(String.valueOf((float)svg.getDocumentWidth()).concat(" x ").concat(String.valueOf((float)svg.getDocumentHeight())));
			
		} catch (IOException d) {
			d.printStackTrace();
			
		} catch (SVGParseException s) {
			s.printStackTrace();
			
		} catch (Exception exception) {
			
			exception.printStackTrace();
		}
	}

```

**Comment by BigBadaboom** [comment]
It will depend on your SVG.

`getDocumentWidth()` and `getDocumentHeight()` return the values of the `width` and `height` attributes, respectively.  Eg.

    <svg width="200" height="150" ,,,>

If your SVG doesn't have those attributes, 0 will be returned.

**Comment by Arashvscode** [comment]
> 

Actually, all my svgs have this option, but it doesn't return anything for me. Is the code I wrote correct?

**Comment by BigBadaboom** [comment]
Can you attach one of your SVGs that doesn't work?

**Comment by Arashvscode** [comment]
> 

Yes, I connected it, but the result is nothing, it returns -1. Can you send me a correct code?

**Comment by BigBadaboom** [comment]
I meant please attach the SVG to this GitHub issue.

**Comment by Arashvscode** [comment]
> 

Actually most of my svgs are 100% length and width, is this a bug in your library?

**Comment by BigBadaboom** [comment]
No. It is not a bug.  It is working as intended.

Those methods were intended to return the dimensions of the SVG -  if they were specified.  But "100%" is not a true dimension.  It means "100% of the viewport or parent container".  But, without knowing those values, "100%" means nothing.

It probably would not be useful to display to your users "100% x 100%". 

Is that is what you actually *do* want to display?  If so, then unfortunately, AndroidSVG doesn't yet have a method to get the exactly value of the `width` and `height` attributes.  For now you would need to fork the code and add those methods yourself.

**Comment by Arashvscode** [comment]
> 

I'd rather you add a converter feature to convert svg to png or vice versa

**Comment by BigBadaboom** [comment]
I don't have any plans to add that feature.
