### ISSUE TITLE
Make fallback color configurable

### ISSUE THREAD

**Issue by mueller-ma** [BigBadaboom/androidsvg#264]
If a svg  doesn't contain any color information, it will be rendered in black. This can cause issues when the icon is used on a dark background as the color ratio is too low then.

Example:

![Screenshot_20230207-182555](https://user-images.githubusercontent.com/96469391/217319805-19aa3750-ae5c-40aa-adba-825dfbe005e1.png)  ![Screenshot_20230207-182635](https://user-images.githubusercontent.com/96469391/217319810-0c5b6c87-3d6a-4dc9-a633-814259f0b927.png) 

Here's another icon without color information:

![window-closed-variant](https://user-images.githubusercontent.com/22525368/218258454-baae8fb1-fd11-411f-88c9-8b9e398a304a.svg)

The icons in this app are user defined, so it's not possible for me to add an color to them. It would help to add a parameter "fallback color" to functions that render a SVG.

**Comment by maniac103** [comment]
> It would help to add a parameter "fallback color" to functions that render a SVG.

... or make that fallback color part of the `RenderOptions`.

**Comment by BigBadaboom** [comment]
You can pass some CSS with the RenderOptions.  Does that not meet your needs?

**Comment by mueller-ma** [comment]
Using CSS to set a value for `currentColor` did it! 👍
