### ISSUE TITLE
SVG Rendering Issue in androidsvg Library

### ISSUE THREAD

**Issue by Nidhi2712** [BigBadaboom/androidsvg#275]
Dear @BigBadaboom,

I hope this message finds you well. I want to start by expressing my gratitude for your work on the [androidsvg](https://github.com/BigBadaboom/androidsvg) library. It has been a valuable library for our development efforts.

I am writing to report an issue we've encountered while using [androidsvg](https://github.com/BigBadaboom/androidsvg) . We are currently developing a product that involves editing SVG images on both Android and iOS platforms. we have been facing some challenges on Android. please review attached images.

The problem we're experiencing is related to SVG rendering. It appears that certain SVGs are not rendering correctly on Android devices, resulting in visual inconsistencies. 

We have thoroughly reviewed our implementation and confirmed that the issue seems to be rooted in the [androidsvg](https://github.com/BigBadaboom/androidsvg)  library itself, as the SVGs in question are well-formed and display correctly on other platforms.

We are eager to continue using [androidsvg](https://github.com/BigBadaboom/androidsvg)  for our Android development, but this rendering issue is currently a roadblock for us. We would greatly appreciate your assistance in resolving this matter or any guidance you can provide to help us better understand and address the issue.

If needed, we can provide specific SVG files and additional details to help diagnose the problem. We understand that open-source projects require time and effort, and we are more than willing to assist in any way we can to resolve this issue.

### **Android SVG Image :**

![Android_SVG](https://github.com/BigBadaboom/androidsvg/assets/63222019/1ebaef9a-46d5-4b6e-904b-ecf95ff03bbf)

### **IOS SVG Image :**

![IOS_SVG](https://github.com/BigBadaboom/androidsvg/assets/63222019/e0c6fec1-8a08-4fae-8571-bbaba2923e7b)

### **SVG String :**

[content_hide_svg.txt](https://github.com/BigBadaboom/androidsvg/files/12514061/content_hide_svg.txt)

Thank you for your attention to this matter, and we look forward to your guidance.

**Comment by BigBadaboom** [comment]
> display correctly on other platforms

I tested your SVG in Chrome and Firefox, and they are rendering it identically to AndroidSVG.

I took a look at your file, and similarly to Issue #274, the `viewBox` in this file is incorrect.  The correct viewBox for this file should be something like "-106 -46 212 258".  If you update the SVG with this corrected viewBox, it should render completely on screen.

So it is actually your IOS library that is rendering the SVG incorrectly.  :)

Hope this helps.

**Comment by Nidhi2712** [comment]
Thanks for the replay, Can you let me know how you calculated the viewbox?

**Comment by BigBadaboom** [comment]
In this case, I used Chrome and the developer tools.

I loaded the SVG into Chrome. Opened the developer console.  Selected the `<svg>` element. Then typed `$0.getBBox()` into the console.

If you are writing an SVG editor, you are going to have to do it yourself programmatically.  Most rendering libraries are probably not going to provide that feature.  However you should be able to get the dimensions of each object via the OS' 2D graphics library.  For example, in Android, you can use methods like `Path.computeBounds()`.
