### ISSUE TITLE
Impossible to include with Android Studio

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#34]
```
When I try to add this library to Android Studio I follow the following method:

1. Download zip of androidsvg lib
2. Unzip
3. (From Android Studio) File -> Import Project...
4. Select the proper input folder
5. Select the proper output folder
6. Leave all settings checked as default

When the importation ends, the androidsvg package still does not appear in the 
interface and no errors are reported.
```

Original issue reported on code.google.com by `fabioloc...@gmail.com` on 8 Apr 2014 at 10:15

**Comment by BigBadaboom** [comment]
Snapshot versions of the upcoming 1.3 release are now available on the Sonatype snapshots repository. 
 If you want to start testing the 1.3 release, instructions on how to do that can be found on the 1.3 release page. http://bigbadaboom.github.io/androidsvg/release-1.3.html

**Comment by devemux86** [comment]
And those who just need the parser can use the regular jar?
```groovy
implementation 'com.caverock:androidsvg:1.3-SNAPSHOT'
```

**Comment by BigBadaboom** [comment]
The jar is not there yet. I wasn't sure whether anyone still wanted jar artifacts.  Can you explain why you prefer them rather than the aar? It's not clear to me.

**Comment by BigBadaboom** [comment]
Yes.  In terms of contents, the only difference between the two formats should be just that small attrs.xml file.  Does that resolve your concerns, or would you still prefer to have a jar available?

**Comment by devemux86** [comment]
In Android "usually" most of xml attributes can be set also in code. So that single AndroidSVG attribute and possibly avoid the complicated (for many users) aar format.

For our libraries we prefer the simple jars, so if cannot use that, we'll have to see how to proceed with any third-party dependencies. :slightly_smiling_face:

**Comment by devemux86** [comment]
#115 seems relevant here.
A good idea would be to split AndroidSVG to core (platform agnostic) module and extra platform modules, e.g. for Android with a View.
That way users who just need the parser can use it easily, without the overload of extra unneeded classes and resources.

**Comment by BigBadaboom** [comment]
I am happy to publish a jar, now that I know people definitely use them.
