### ISSUE TITLE
Speed Improvements with kXML

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#36]
```
We are using svg-android-2 in the mapsforge project.
But with a main change, the use of the kXML library which speeds up SVG parsing 
considerably, compared with the SAX version.

I have tried also androidsvg which seems to use SAX.
Though it could render more svg files, it's slower than above implementation.

Have you considered using a faster SVG parser like the kXML?
```

Original issue reported on code.google.com by `devemu...@gmail.com` on 11 Jun 2014 at 8:02

**Comment by BigBadaboom** [comment]
As part of the fix for issue #122, the parser now uses XmlPullParser by default instead of SAXParser.
There does seem to be a good speed improvement. For example one large file I tested was parsed 40% more quickly.

Hence, I'm going to close this bug as fixed for now.
