### ISSUE TITLE
SVGAndroidRenderer.processMaskBitmaps is very slow

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#45]
```
What steps will reproduce the problem?
1. Render the attached test.svg using renderToCanvas

What is the expected output? What do you see instead?
For a small file like this, I'd have expected a few ms to render. Instead, it 
took 200ms - 300ms. Using renderToPicture, and rendering the picture it was 
only 15ms.

I profiled it, and processMaskBitmaps was the major bottleneck. Instead of the 
custom processing, I'd guess drawBitmap using a PorterDuffXfermode would work 
here, too. E.g. paint.setXfermode(new PorterDuffXfermode(Mode.DST_IN));


```

Original issue reported on code.google.com by `mar...@greenrobot.de` on 17 Aug 2014 at 8:41

Attachments:
- [test.svg](https://storage.googleapis.com/google-code-attachments/androidsvg/issue-45/comment-0/test.svg)

**Comment by BigBadaboom** [comment]
Note to self: need to fix the mask routine. It currently uses a bitmap the size of the whole canvas for the mask buffer.  This uses a lot of memory if there are a lot of nested masks. Should use buffer the size of the original object - or use a different technique.

**Comment by BigBadaboom** [comment]
Fixed.

**Comment by BigBadaboom** [comment]
TODO: Update the documentation on 1.3 release:

Rendering of masks no longer requires the use of renderToCanvas().

**Comment by devemux86** [comment]
Android P makes these changes and the use of [Canvas.ALL_SAVE_FLAG](https://developer.android.com/reference/android/graphics/Canvas#ALL_SAVE_FLAG) somehow mandatory.
If use `targetSdkVersion 28` the AndroidSVG Maven current release does not work, throwing:
```java
IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
```
So with latest Android need to use the AndroidSVG snapshot version instead.
