### ISSUE TITLE
SVGImageView crashes on Android 5.0 and higher

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#60]
```
What steps will reproduce the problem?
Using the following code will crash 5.0 and above with a segfault from the OS:

private FrameLayout mIdCardContainer;
private SVGImageView mIdCardBackImage;
private SVGImageView mIdCardFrontImage;

mIdCardFrontImage = new SVGImageView(getActivity());
mIdCardFrontImage.setId(R.id.img_id_card_front);
mIdCardFrontImage.setLayoutParams(new 
ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, 
ViewGroup.LayoutParams.MATCH_PARENT));
mIdCardFrontImage.setContentDescription(getString(R.string.front_of_id_card));
mIdCardFrontImage.setRotation(ROTATION_ANGLE);


// Setup special SVGImageViews for back of card
mIdCardBackImage = new SVGImageView(getActivity());
mIdCardBackImage.setId(R.id.img_id_card_back);
mIdCardBackImage.setLayoutParams(new 
ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, 
ViewGroup.LayoutParams.MATCH_PARENT));
mIdCardBackImage.setContentDescription(getString(R.string.back_of_id_card));
mIdCardBackImage.setRotation(ROTATION_ANGLE);
mIdCardBackImage.setVisibility(View.GONE);


SVG frontSvg = SVG.getFromString( idCard.getCardFrontData() );
SVG backSvg = SVG.getFromString( idCard.getCardBackData() );

mIdCardFrontImage.setSVG(frontSvg);
mIdCardBackImage.setSVG(backSvg);

What is the expected output? What do you see instead?
Some devices crash immediately on setting the images others fail miserably when 
the two images are flipped with an animation front -> tap -> back -> tap -> 
crash

What version of the product are you using? On what operating system?
1.2.2-beta-1

Please provide any additional information below.
This works fine on 4.1-4.4.2
This does not work at all on Genymotion, or on certain devices.
The crash after flipping back to the front image crashes on the Samsung S6 
running 5.0.2, but works on a nexus 5 running 5.0.


```

Original issue reported on code.google.com by `troo...@itriagehealth.com` on 7 May 2015 at 6:47

**Comment by Mauker1** [comment]
I'm not sure if it's a problem with the SVG lib or skia itself, but I'm also facing a similar problem.

I've opened [this question](http://stackoverflow.com/questions/36507316/app-random-crashes-with-fatal-signal-7-sigbus-code-2-or-fatal-signal-11-sigs) on StackOverflow to try to find out why is this happening.

**Comment by BigBadaboom** [comment]
It must be frustrating. Are you (a) sure it's not an OOM issue as the Skia person suspects, and (b) able to create a minimal app that triggers that crash?

**Comment by Mauker1** [comment]
It is frustrating. Struggling with this issue for months :/

a) I'm not that sure. But idk, even when I removed all the other images of my app, the crash still occurred. 

b) I can. If it helps to find the issue :) 

I've already shared some details on the question. I don't know if I should copy and paste those info here as well. But I can also do that if it helps.

**Comment by BigBadaboom** [comment]
I don't think there is much I personally can do about this.  I was really thinking that if we want the Skia folks to take it seriously (and reopen the bug) they will need to be provided with something they can reproduce the crash with.  Otherwise it will remain ignored.

**Comment by Mauker1** [comment]
Yeah, good thinking. I think I'll make that sample crashing app. Thank you for your time :)

**Comment by BigBadaboom** [comment]
Closing this old report. Did you ever find a solution?

**Comment by Viraj7009** [comment]
Hi @BigBadaboom I'm getting this below crash when trying to re-render the SVG when flipping the SVG between front and back. This crash is happening on Android OS below 8.0. The flipping works on newer OS's like 10.0 and 11.0 but on older OS's it crashes the app with below log. Any idea why it would crash at this line in SVG library in SVGAndroidRenderer class Line#1969. I checked I have a valid image and a valid paint and canvas object.

canvas.drawBitmap(image, 0, 0, bmPaint); 



A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 14586 (package name), pid 14586 (package name)

**Comment by BigBadaboom** [comment]
Thanks for your report.  Can you please create a new issue with a little more info please?

- What does "flipping between front and back" mean?  Are you showing two different images?  Or are you using CSS to hide and show different parts of the same SVG?  Or something else?  What does that mean in code terms?
- By "re-render", do you mean that it works the first time, but not after that?  Is it intermittent (ie renders sometimes, randomly)?
- What type of bitmap image is it (PNG, JPG)?
- Are you using SVGImageView, or rendering to the screen yourself?
- Have you tried bypassing AndroidSVG, and rendering that bitmap directly to the canvas yourself?  In other words, does it render successfully outside of AndroidSVG?
- Does it just happen with just that one specific bitmap, or other bitmaps also?

Please attach the SVG, or a minimal version of it, thatl reproduces the problem.  I won't be able to investigate without being able to reproduce the crash.

SEG faults typically indicate an OS bug.  So realistically, it is probably not something I will be able to do much about.  But please create a new issue with the requested details, and I will take a look.

Regards
Paul

**Comment by Viraj7009** [comment]
Hi @BigBadaboom sorry for late reply but it was a weird error. I think I was trying to redraw the image on the same canvas and it was causing issues. I just removed the redrawing logic and everything works fine. Thanks for your help.

**Comment by BigBadaboom** [comment]
Hi Viraj

Weird.  Redrawing on the same canvas should still be fine.  If you are able to reproduce the error, I would still be interested in taking a look at why it happened.
