### ISSUE TITLE
 Incorrect rendering of SVG image

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#63]
```
What steps will reproduce the problem?
1. Render the atttached file.

What is the expected output? What do you see instead?
Should be simple menu with 3 horizontal bars but only background.




```

Original issue reported on code.google.com by `jakub.zi...@gmail.com` on 15 May 2015 at 12:35

Attachments:
- [menu.svg](https://storage.googleapis.com/google-code-attachments/androidsvg/issue-63/comment-0/menu.svg)

**Comment by BigBadaboom** [comment]
Closing this bug as the file renders as expected. Our rendering matches the browsers. I can't see any difference.  File was tested in AndroidSVG releases 1.2.1, 1.2.2-beta1, and the current master branch.
