### ISSUE TITLE
renderToCanvas(Canvas canvas, RectF viewPort) viewPort ignored?

### ISSUE THREAD

**Issue by wonson** [BigBadaboom/androidsvg#78]
I dunno if I get the meaning of this method wrong, but this is nothing different from renderToCanvas(Canvas canvas).

When I trace the code, I see viewPort is assigned to state.viewPort in resetState(). Then in render(SVG.Svg obj, Length width, Length height, Box viewBox, PreserveAspectRatio positioning) state.viewPort is immediately replaced by another new Box?

**Comment by BigBadaboom** [comment]
> state.viewPort is immediately replaced by another new Box?

But that new box is itself initialised with values from state.viewPort.  Is that renderToCanvas() method not working?  If so I'll take a look at it.

**Comment by wonson** [comment]
Its because 
    render(rootObj, rootObj.width, rootObj.height,
             (viewBox != null) ? viewBox : rootObj.viewBox,
             (positioning != null) ? positioning : rootObj.preserveAspectRatio);

width and height input with rootObj.width, rootObj.height, so state.viewPort params are not used in
    float  _w = (width != null) ? width.floatValueX(this) : viewPortUser.width;  // default 100%
      float  _h = (height != null) ? height.floatValueY(this) : viewPortUser.height;

**Comment by BigBadaboom** [comment]
Fixed finally!

@wonson Thanks for the original bug report.
