### ISSUE TITLE
ImageView fitXY 

### ISSUE THREAD

**Issue by frgossen** [BigBadaboom/androidsvg#79]
I use SVG graphics in ImagesViews as it is described on the website (http://bigbadaboom.github.io/androidsvg/use_with_ImageView.html). This works perfectly unless the ImageView's scaleType is set to "fitXY" in which case the behaviour is not as expected. The image should be scaled in width and height to fit the ImageView but is actually displayed much smaller in the upper left corner of the ImageView. 

This is how I load the SVG file: 

```
    try {
        ImageView imageView = (ImageView) findViewById(imageViewId);
        imageView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
        SVG svg = SVG.getFromResource(this, imageResourceId);
        svg.setRenderDPI(getResources().getDisplayMetrics().xdpi);
        Drawable drawable = new PictureDrawable(svg.renderToPicture());
        imageView.setImageDrawable(drawable);
    } catch (SVGParseException e) {
        e.printStackTrace();
    }
```

For my ImageView I can set the scale type in the XML layout file. This also works for drawables that I set programmatically. I tried it with a PNG file as follows. 

```
    ImageView imageViewChoosePlayerAny = (ImageView) findViewById(R.id.choose_player_0);
    imageViewChoosePlayerAny.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
    Drawable drawable = getResources().getDrawable(R.drawable.pointer);
    imageViewChoosePlayerAny.setImageDrawable(drawable);
```

The corresponding part in the XML layout file is as follows. 

```
        <ImageView
            android:id="@+id/choose_player_0"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="@color/player_0"
            android:onClick="onPlayer0"
            android:scaleType="fitXY"/>
```

For the PNG file this works perfectly while for the SVG as discussed above it does not. All images are loaded in the onCreate method: 

```
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_choose_player);

    player = getIntent().getParcelableExtra("player");

    loadVectorGraphics();

    Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
    setSupportActionBar(toolbar);
    getSupportActionBar().setDisplayHomeAsUpEnabled(true);
}
```

**Comment by BigBadaboom** [comment]
Sorry it took me so long to look into this.

After some investigation it seems that scaleTypes `fitXY` and `center` do not work with PictureDrawables.
`fitXY` does no scaling at all, and `center` causes the ImageView to seeming not render at all.

I have filed a bug report with Google here.
https://issuetracker.google.com/issues/72137551

Unfortunately, I don't think there is anything I can do to work around this bug.  It seems to have existed for a long time. I tested back to Ice Cream Sandwich (4.0.3).

All I can do is update the documentation to help future people who strike this problem.

**Comment by BigBadaboom** [comment]
I have updated the FAQ question related to ScaleType.CENTER to also cover ScaleType.FIT_XY.

Marking closed, as there is nothing I can do on my end to fix this.

**Comment by Nasiralityagi** [comment]
Hi Coders,
When you render your SVG in your "SVGImageView.java" 
Just use custom DrawablePicture
        `Picture picture = this.svg.renderToPicture(renderOptions);
        setImageDrawable(new SharpDrawable(picture));
        setScaleType(ScaleType.FIT_XY);`

Below is the class of "SharpDrawable.java"

import android.annotation.TargetApi;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Picture;
import android.graphics.Rect;
import android.graphics.drawable.PictureDrawable;
import android.os.Build;
import android.os.Looper;
import android.support.annotation.Nullable;
import android.util.Log;
import android.view.View;

public class SharpDrawable extends PictureDrawable {

    private static final String TAG = SharpDrawable.class.getSimpleName();

    private static final Bitmap.Config CACHE_CONFIG = Bitmap.Config.ARGB_8888;

    private float mScaleX = 1f;
    private float mScaleY = 1f;

    private boolean mCaching = false;
    private Rect mCacheBounds;
    private Bitmap mCacheBitmap;
    private float mCacheScale = 1f;


    @TargetApi(Build.VERSION_CODES.HONEYCOMB)
    public SharpDrawable(@Nullable Picture picture) {
        super(picture);
    }

    @TargetApi(Build.VERSION_CODES.HONEYCOMB)
    public SharpDrawable(@Nullable View view, @Nullable Picture picture) {
        super(picture);
        prepareView(view);
    }

    private static void prepareView(@Nullable final View view) {
        if (view != null && Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
            if (Looper.myLooper() == Looper.getMainLooper()) {
                view.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
            } else {
                view.post(new Runnable() {
                    @Override
                    public void run() {
                        view.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
                    }
                });
            }
        }
    }

    @Override
    public void draw(Canvas parentCanvas) {
        long start = System.currentTimeMillis();
        Picture picture = getPicture();
        if (picture != null) {
            Rect bounds = getBounds();
            Canvas canvas = null;
            if (mCaching) {
                if (mCacheBitmap == null || mCacheBounds == null || !mCacheBounds.equals(bounds)) {
                    // Redraw needed
                    resetCache();
                    // creates a new mutable bitmap
                    int w = (int) (bounds.width() * mCacheScale);
                    int h = (int) (bounds.height() * mCacheScale);
                    Log.v(TAG, "cache bitmap " + w + "x" + h);
                    mCacheBitmap = Bitmap.createBitmap(
                            w,
                            h,
                            CACHE_CONFIG);
                    if (mCacheBounds == null) {
                        mCacheBounds = new Rect(bounds);
                    } else {
                        mCacheBounds.set(bounds);
                    }
                    // start drawing onto this bitmap
                    canvas = new Canvas(mCacheBitmap);
                    canvas.save();
                    canvas.scale(mCacheScale, mCacheScale);
                }
            } else {
                canvas = parentCanvas;
            }
            if (canvas != null) {
                canvas.save();
                canvas.clipRect(bounds);
                Log.v(TAG, "canvas " + canvas.getWidth() + "x" + canvas.getHeight());
                Log.v(TAG, "bounds " + bounds.toString());
                canvas.translate(bounds.left, bounds.top);
                canvas.scale(mScaleX, mScaleY, 0, 0);
                canvas.drawPicture(picture);
                canvas.restore();
            }
            if (mCacheBitmap != null) {
                if (canvas != null) {
                    canvas.restore();
                }
                parentCanvas.save();
                parentCanvas.scale(1f / mCacheScale, 1f / mCacheScale, 0, 0);
                parentCanvas.drawBitmap(mCacheBitmap, 0, 0, null);
                parentCanvas.restore();
            }
        }
        Log.v(TAG, "Drawing " + hashCode() + " complete in " + (System.currentTimeMillis() - start) + " ms.");
    }

    @Override
    public void setBounds(int left, int top, int right, int bottom) {
        Picture picture = getPicture();
        int width = right - left;
        int height = bottom - top;
        mScaleX = (float) width / (float) picture.getWidth();
        mScaleY = (float) height / (float) picture.getHeight();
        super.setBounds(left, top, right, bottom);
    }

    @SuppressWarnings("unused")
    public void setCaching(boolean caching) {
        mCaching = caching;
    }

    @SuppressWarnings("unused")
    public void setCacheScale(float scale) {
        mCacheScale = scale;
    }

    @SuppressWarnings("unused")
    public void resetCache() {
        if (!mCaching) {
            throw new IllegalStateException("Cache is not enabled");
        }
        if (mCacheBitmap != null) {
            // recycle the old bitmap
            mCacheBitmap.recycle();
            mCacheBitmap = null;
        }
    }

    public Bitmap getCacheImage() {
        return mCacheBitmap;
    }
}

**Comment by stefanhaustein** [comment]
One option to work around this bug would be to add a custom drawable that wraps PictureDrawable and re-creates it as needed, see https://github.com/stefanhaustein/emojisprites/blob/master/core/src/main/java/org/kobjects/graphics/SvgDrawable.java

Happy to create a pull request if this makes sense for you...

**Comment by BigBadaboom** [comment]
Google have fixed this bug supposedly (I haven't checked to see which version of Android has the fix).  And since I'm planning on having a new SVGView in the next version that renders directly, I'm not sure that it's worth integrating this fix into AndroidSVG.

I'm open to counter-arguments, but in the meantime, at least there are solutions her for those that this bug affects.

**Comment by stefanhaustein** [comment]
One counter argument could be that a view is not the right abstraction for everybody / all applications. For instance, I plan to swap out the svg drawable for a bitmap drawable dynamically below a certain size (where the bitmap is shared between different views) inside an ImageView that persists. Generally it seems preferable to address problems at the lowest possible layer? Drawables can be used in more places than Views.
