### ISSUE TITLE
Custom fonts.

### ISSUE THREAD

**Issue by vitorprado** [BigBadaboom/androidsvg#83]
I'm trying to render a magazine page in SVG.. and I need to render the custom font.. but it doesn't render `<text>` tags with my custom `@font-face`.

**Comment by BigBadaboom** [comment]
`@font-face` probably won't be ever be supported.  AndroidSVG doesn't do any fetching of resources by itself.  It relies on you providing those resources via an `SVGExternalFileResolver`.

It is easy to use custom fonts:
1. Put your `.ttf` files in the `assets` folder
2. Tell AndroidSVG to use `SimpleAssetResolver`, which is a sample implementation of `SVGExternalFileResolver` provided with the library
3. You just need to make sure the font name in your SVG/CSS matches the filename (minus extension) of the TTF file.

Or, if you want, you can make your own resolver implementation which fetches the fonts from some other location.

**Comment by BigBadaboom** [comment]
Marking Won't Fix

**Comment by vitorprado** [comment]
I'm using `@font-face` with base64.. not relative to the file.
I will try using `.ttf` fonts.. thanks!
