### ISSUE TITLE
getViewList return size 0

### ISSUE THREAD

**Issue by pangff** [BigBadaboom/androidsvg#85]
I use Svg.getViewList() return size 0. I found SVG  getViewList source code this.getElementsByTagName(SVG.View.class) with param SVG.View.class but SVG.SvgContainer obj getClass() is SVG.Svg.class . It's an bug or my Svg document is wrong

**Comment by BigBadaboom** [comment]
Thanks for your report. Sorry for not responding at the time.

I've just been testing this, and found no errors.  Are you sure your SVG contains a `<view>` element?
If so, please provide a test file and show how you are calling the `getViewList()` method.

For now I am going to mark this as "works for me".
