### ISSUE TITLE
Can we loosen the xlink:href checking?

### ISSUE THREAD

**Issue by TWiStErRob** [BigBadaboom/androidsvg#89]
`SVGParser` is checking `XLINK_NAMESPACE` a lot when querying `href` attributes.

I investigated this because my code editor (IntelliJ IDEA 2016.1.2) doesn't agree with using the `xlink` namespace. I also reported [this Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=611366) earlier where I found that IE11, Chrome 50 both support both `xlink:href` and unqualified `href`. FF43 works like AndroidSVG though, ignoring unqualified `href` attributes and accepting only `xlink:href`.

[Digging deep into SVG's DTD](https://youtrack.jetbrains.com/issue/IDEA-155961) it seems to me that AndroidSVG/FF's approach is the correct standards-conforming one. What do you think about this?

**Comment by BigBadaboom** [comment]
As you say, checking the namespace is the correct behaviour for SVG 1.1 parsers.  The ability to use plain `href` attributes is part of the (still draft) SVG2 specification.  Some browsers have started implementing features of SVG2.  That explains Chrome's behaviour.  I will also sooner or later.

**Comment by TWiStErRob** [comment]
Ah that makes sense, thank you for clearing that up.

In case someone is interested here are some links:
https://www.w3.org/TR/SVG2/embedded.html#ImageElementHrefAttribute
https://www.w3.org/TR/SVG2/linking.html#XLinkRefAttrs

**Comment by BigBadaboom** [comment]
Fixed.

Added support for SVG2 href attributes without the xlink namespace.

**Comment by TWiStErRob** [comment]
Awesome! Thanks. You seem to be reactivating, 1.2.3, 1.3 coming up?

**Comment by BigBadaboom** [comment]
For now I had some time, so just trying to clear the issue backlog. :) 
Not sure yet what's going into the next release.
