### ISSUE TITLE
xml namespace can not recognize

### ISSUE THREAD

**Issue by caoyunxuan07** [BigBadaboom/androidsvg#91]
when i use

```
<com.caverock.androidsvg.SVGImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop"
        app:svg="@drawable/header"/>
```

(header is a .xml file which is transformed from .svg)
in a layout xml file

either i add`xmlns:app="http://schemas.android.com/apk/res-auto"`
or`xmlns:app="http://schemas.android.com/apk/res/com.caverock.androidsvg.SVGImageView"`
or`xmlns:app="http://schemas.android.com/apk/lib/com.caverock.androidsvg.SVGImageView"`
in root tag's attribute, application cant run! it will failed when load layout file.

**Comment by caoyunxuan07** [comment]
#73 cannot resolve for me, maybe the source version that i download is not correspond to compile  version that dependency from Maven in my project(by the way, why can i only dependency the lastest version from Maven?)
```
<declare-styleable name="SvgImageView">
		<attr name="android:src"/>
	</declare-styleable>
	<declare-styleable name="SvgDrawable">
		<attr name="android:src"/>
		<attr name="android:antialias"/>
		<attr name="android:filter"/>
		<attr name="android:dither"/>
		<attr name="android:gravity"/>
	</declare-styleable>
```
there is no `svg `attr

**Comment by BigBadaboom** [comment]
Hi.  Try the solution in Issue #76. Hopefully that will fix your problem.

**Comment by BigBadaboom** [comment]
Did that fix your problem?

**Comment by caoyunxuan07** [comment]
Sorry for late. And NO! IDE dont raise error, but throw a Exception when create view.

`Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.caverock.androidsvg.SVGImageView`
and i can use this class by java code
`com.caverock.androidsvg.SVGImageView s = new SVGImageView(this);`
i search on web but cant find any useful general solution.

<br/>i get library dependency from maven.
`compile 'com.caverock:androidsvg:1.2.0'`(or 1.2.2-beta, same problem.)

**Comment by BigBadaboom** [comment]
That's the error you get when you don't have the attrs.xml file copied to the correct place.  Have you done that?  You will also need the res-auto line in the root element. of your layout file

http://stackoverflow.com/questions/34990236/how-to-use-svg-image-in-imageview

**Comment by caoyunxuan07** [comment]
yes, sure, done everything

<h3>layout/navheader.xml </h3>
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="@dimen/navheader_height"
    android:background="?attr/colorPrimaryDark"
    android:orientation="vertical"
    android:padding="0dp">
    <com.caverock.androidsvg.SVGImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop"
        app:svg="@drawable/header" />

</LinearLayout>
```

<h3>build.gradle</h3>
```
dependencies {
    compile 'com.caverock:androidsvg:1.2.0'
}
```

<h3>attrs.xml</h3>
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<!--TODO for app:svg attribute-->
	<declare-styleable name="SVGImageView">
		<!-- Location of the SVG document. -->
		<attr name="svg" format="reference|string"/>
	</declare-styleable>
</resources>
```

**Comment by BigBadaboom** [comment]
Hmm.. .What you have done looks okay.   A couple of ideas to try:

1. Are you using any ProGuard rules that might be removing the SVGImageView class?
2. Try moving your file to `assets/header.svg` and using `app:svg="header.svg"`.

**Comment by vikramkakkar** [comment]
@caoyunxuan07 Can you post the entire stack-trace? Please make sure that the stack-trace isn't truncated in LogCat itself.

**Comment by BigBadaboom** [comment]
Closing this old help issue. I am going to assume that the OPs problems were resolved.
