### ISSUE TITLE
Could I use svg as background of SVGImageView

### ISSUE THREAD

**Issue by Cyux07** [BigBadaboom/androidsvg#92]
the attribute 'svg' in SVGImageView look like 'src' in normal ImageView, so could i somehow set 'background'?

**Comment by BigBadaboom** [comment]
Hi

No.  SVGImageView only allows you to set a "foreground" image.  You could layer two Views in top of one another using a FrameLayout. Put SVGImageView forst (ie. at the back) and whatever you like on top of it.

If you have any other questions, please use the androidsvgfeedback@gmail.com address.  This Issues feature of github is for bug reports and feature requests only.

**Comment by caoyunxuan07** [comment]
OK, Sorry about this, but i think issue has `enhancement `label

**Comment by BigBadaboom** [comment]
Were you asking to be able to set an SVG as the background of an SVGImageView?

**Comment by caoyunxuan07** [comment]
yes,yes,could you?😇
two views look like carrying too much memory

**Comment by BigBadaboom** [comment]
I am going to close this issue as Won't Fix.  I don't think that this is a very useful feature.  Most people will be happy with layering two SVGImageViews. And even if I did implement it, it would be made redundant when I finish implementing DOM support (#130).
