### ISSUE TITLE
VTM uses AndroidSVG

### ISSUE THREAD

**Issue by devemux86** [BigBadaboom/androidsvg#97]
Hi @BigBadaboom,

As known [Mapsforge](https://github.com/mapsforge/mapsforge) vector map library already uses AndroidSVG for the render themes.

I integrated AndroidSVG also in [VTM](https://github.com/mapsforge/vtm) vector map library for svg resources (https://github.com/mapsforge/vtm/issues/60).

You can see it in action in [Cruiser](http://wiki.openstreetmap.org/wiki/Cruiser) for both Mapsforge and VTM rendering.

_Sorry if issues list isn't the right place to mention AndroidSVG's use cases._

**Comment by BigBadaboom** [comment]
Thanks for letting me know!
